/* Catalog filters and previews never write the active outfit. */
(function(g){'use strict';var C=g.CPW,D=C.data,U=C.util,E=C.ui.el;
function normalize(q){return String(q||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,function(c){return String.fromCharCode(c.charCodeAt(0)-96);}).trim();}
function filter(f){var terms=normalize(f.query).split(/\s+/).filter(Boolean),seen={};return D.presets.filter(function(p){if(seen[p.id])return false;seen[p.id]=true;var hay=normalize([p.labelJa,p.summaryJa].concat(p.moodTags,p.searchAliases||[]).join(' '));return (!f.category||p.categoryId===f.category)&&(!f.mood||p.moodTags.indexOf(f.mood)>=0)&&terms.every(function(t){return hay.includes(t);});});}
function pick(list,last,rng){var choices=list.length>1?list.filter(function(p){return p.id!==last;}):list;return choices.length?choices[Math.floor((rng||Math.random)()*choices.length)]:null;}
function create(id){var p=U.byId(D.presets,id);if(!p)throw Error('Unknown preset');var o=C.schema.applyPatch(C.schema.createOutfit(),p.patch);o.name=p.labelJa;o.entryMode='preset';return o;}
function adopt(outfit){var before=C.state.outfit,dirty=C.state.dirty,saved=C.state.savedId;try{var next=C.schema.normalize(U.clone(outfit));C.state.load(next);return next;}catch(e){C.state.outfit=before;C.state.dirty=dirty;C.state.savedId=saved;C._autosave();throw e;}}
function button(t,fn,attrs){return E('button',Object.assign({type:'button',class:'btn',text:t,onclick:fn},attrs));}
function swatches(o){var box=E('div',{class:'discovery-swatches'});['primary','secondary','accent'].forEach(function(k){var c=U.byId(D.colors,o.palette[k]);if(c){var s=E('span',{class:'discovery-swatch',title:c.labelJa,'aria-label':c.labelJa});s.style.backgroundColor=c.hex;box.appendChild(s);box.appendChild(E('span',{text:c.labelJa}));}});return box;}
var browsing={query:'',category:'',mood:'',scroll:0},last=null;
function view(){var host=E('section',{class:'screen discovery'}),draft=null,chosen=null,confirming=false,message='',applied=false,colorOpen=false;
function goPreview(p){if(!draft)browsing.scroll=g.scrollY;chosen=p;last=p.id;draft=create(p.id);confirming=false;applied=false;message='';drawPreview();g.scrollTo(0,0);host.querySelector('h1').focus();}
function back(){draft=null;drawList();g.scrollTo(0,browsing.scroll);var card=host.querySelector('[data-preset="'+last+'"]');if(card)card.focus({preventScroll:true});}
function doAdopt(){if(!confirming&&(C.state.outfit.garment.subtype||C.state.outfit.name||C.state.dirty)){confirming=true;drawPreview();host.querySelector('[data-preset-confirm]').focus();return;}try{adopt(draft);applied=true;confirming=false;message='この衣装を使い始めました。';drawPreview();host.querySelector('[data-after-adopt]').focus();}catch(e){message='衣装を採用できませんでした。現在の設計は保持しています。';confirming=false;drawPreview();console.error(e);}}
function drawPreview(){host.replaceChildren(E('a',{href:'#/',class:'back-btn',text:'← 開始画面'}),E('h1',{class:'page-title',tabindex:'-1',text:chosen.labelJa}),E('p',{class:'p',text:chosen.summaryJa}),swatches(draft),E('p',{class:'p p--note',text:'衣装データのプレビューです。画像生成の結果ではありません。'}),E('p',{class:'prompt-text',text:C.generator.short(draft)}));
if(message)host.appendChild(E('p',{role:'status',text:message}));
if(applied){[['#/output','プロンプトを見る'],['#/presentation','ポーズを選ぶ'],['#/workshop','細かく編集']].forEach(function(a){host.appendChild(E('a',{href:a[0],class:'btn','data-after-adopt':'true',text:a[1]}));});host.appendChild(button('一覧に戻る',back));return;}
host.appendChild(button('配色を変える',function(){colorOpen=!colorOpen;drawPreview();},{'aria-expanded':String(colorOpen)}));
if(colorOpen){['primary','secondary','accent'].forEach(function(k,i){var id='preview-color-'+k,select=E('select',{id:id,class:'cf-select'});select.appendChild(E('option',{value:'',text:'未選択'}));D.colors.forEach(function(c){select.appendChild(E('option',{value:c.id,text:c.labelJa}));});select.value=draft.palette[k]||'';select.addEventListener('change',function(){draft.palette[k]=select.value||null;drawPreview();});host.appendChild(E('label',{for:id,text:['主色','副色','差し色'][i]}));host.appendChild(select);});}
if(confirming){host.appendChild(E('p',{text:'現在の衣装を置き換えます。未保存の変更も置き換わります。',class:'p p--warn'}));host.appendChild(button('この衣装に置き換える',doAdopt,{'data-preset-confirm':'true'}));host.appendChild(button('キャンセル',function(){confirming=false;drawPreview();host.querySelector('[data-preset-adopt]').focus();}));}
else host.appendChild(button('この衣装を使う',doAdopt,{'data-preset-adopt':'true',class:'btn btn--primary'}));
var list=filter(browsing);host.appendChild(button('別の候補を見る',function(){var p=pick(list,last);if(p)goPreview(p);},{disabled:!list.length}));host.appendChild(button('一覧に戻る',back));}
function drawList(){host.replaceChildren(E('a',{href:'#/',class:'back-btn',text:'← 開始画面'}),E('h1',{class:'page-title',text:'プリセットから遊ぶ'}),E('p',{class:'p',text:'衣装を試して、気に入ったら使い始めましょう。'}));var search=E('input',{id:'preset-search',type:'search',class:'name-input',placeholder:'名前・説明・別名で検索'});search.value=browsing.query;host.appendChild(E('label',{for:'preset-search',text:'衣装を検索'}));host.appendChild(search);
function select(id,label,rows,key){var s=E('select',{id:id,class:'cf-select'});s.appendChild(E('option',{value:'',text:'すべて'}));rows.forEach(function(r){s.appendChild(E('option',{value:r.id,text:r.labelJa}));});s.value=browsing[key];s.addEventListener('change',function(){browsing[key]=s.value;results();});host.appendChild(E('label',{for:id,text:label}));host.appendChild(s);}
select('preset-category','主分類',D.presetCategories,'category');select('preset-mood','雰囲気',D.presetMoods.map(function(m){return {id:m,labelJa:m};}),'mood');
var count=E('p',{role:'status',id:'preset-count'}),random=button('この条件でおまかせ',function(){var p=pick(filter(browsing),last);if(p)goPreview(p);},{id:'preset-random'}),cards=E('div',{class:'discovery-grid'});host.appendChild(count);host.appendChild(button('絞り込みを解除',function(){browsing.query=browsing.category=browsing.mood='';search.value='';host.querySelector('#preset-category').value='';host.querySelector('#preset-mood').value='';results();}));host.appendChild(random);host.appendChild(cards);
function results(){var list=filter(browsing);count.textContent=list.length+'件';random.disabled=!list.length;cards.replaceChildren();if(!list.length)cards.appendChild(E('p',{text:'一致する衣装がありません。絞り込みを解除してください。'}));list.forEach(function(p){var b=button('',function(){goPreview(p);},{class:'card card--tap','data-preset':p.id});b.appendChild(E('h2',{class:'card-title',text:p.labelJa}));b.appendChild(E('p',{class:'p',text:p.summaryJa}));b.appendChild(E('p',{class:'p p--note',text:p.moodTags.slice(0,3).join('・')}));b.appendChild(swatches(create(p.id)));cards.appendChild(b);});}
search.addEventListener('input',function(){browsing.query=search.value;results();});results();}
drawList();return host;}
C.presetCatalog={normalizeSearch:normalize,filter:filter,pick:pick,create:create,adopt:adopt,view:view};C.routes['/presets']=view;
})(window);
