/* New edits use separated pose/framing fields; untouched legacy data uses the old generator. */
(function(g){'use strict';var C=g.CPW,P=C.data.presentation,U=C.util,E=C.ui.el,baseNormalize=C.presentation.normalize,baseBlocks=C.presentation.blocks;
var supports={sit:['chair','armchair','throne','stool','bench','sofa','counter_chair','church_chair','school_chair','garden_chair','bar_stool','bed','cushion','stairs','rock','waterside'],chair:['chair','armchair','throne','stool','bench','counter_chair','church_chair','school_chair','garden_chair','bar_stool'],backrest:['chair','armchair','throne','church_chair','school_chair','garden_chair'],floor:['floor','cushion','flower_field'],sofa:['sofa'],bed_sit:['bed'],lie:['floor','bed','chaise'],chaise:['chaise']};
function known(list,id){return U.byId(list,id)?id:null;}
C.presentation.normalize=function(raw){var p=baseNormalize(raw);if(raw&&raw.layoutVersion===1){p.layoutVersion=1;p.poseId=known(P.poseChoices,raw.poseId);p.distanceId=known(P.distances,raw.distanceId);p.angleId=known(P.angles,raw.angleId);}return p;};
function editable(raw){var p=C.presentation.normalize(raw);if(p.layoutVersion===1)return p;var m=U.byId(C.data.presentationLegacyMap,p.preset),assist={standing:'standing',walking:'runway',seated:'seated'};p.layoutVersion=1;p.poseId=m?m.poseId:(assist[p.poseAssist]||null);p.distanceId=m?m.distanceId:({full_outfit:p.poseAssist?'full':null,upper_body:'upper',detail:'face'}[p.focus]||null);p.angleId=m?m.angleId:(p.compositionAssist==='low_angle'?'low':null);p.preset=null;p.focus=null;p.poseAssist=null;if(p.compositionAssist!=='plain_bg')p.compositionAssist=null;return p;}
function feature(o,key){var parts=o.parts||{},sub=o.garment.subtype||'',cat=U.byId(C.data.garmentCategories,o.garment.category),active=cat?cat.slots:[];
function has(slot){return active.indexOf(slot)>=0&&parts[slot]&&parts[slot]!=='no_'+slot;}
if(key==='cape')return sub==='cape_coat'||has('cover_up')&&(parts.cover_up==='full_back_cape'||parts.cover_up==='shoulder_cape')||has('asymmetry_detail')&&JSON.stringify(parts.asymmetry_detail).includes('one_sided_cape');
if(key==='coat')return ['long_coat','trench_coat','fur_coat','cape_coat','laboratory_coat_outfit','eastern_cloak_robe'].indexOf(sub)>=0;
if(key==='collar')return has('collar')||['business_suit','shirt_and_trousers','suspender_shirt_trousers','linen_shirt_wide_trousers','buttoned_pajama_set','tailcoat_suit','flight_suit'].indexOf(sub)>=0;
if(key==='sleeves')return has('sleeves')&&parts.sleeves!=='sleeveless'||!parts.sleeves&&['business_suit','long_coat','tailcoat_suit','flight_suit','shirt_and_trousers','buttoned_pajama_set'].indexOf(sub)>=0;
if(key==='skirt')return o.garment.category==='dress'||['knit_and_skirt','oversized_knit_long_skirt','cardigan_and_long_skirt'].indexOf(sub)>=0;
if(key==='backDecoration')return o.decorations.items.some(function(i){return U.byId(C.data.decorations,i.type)&&(i.placements||[]).indexOf('back')>=0;});return true;}
function reason(o,pose){if(!pose)return '';if(o.garment.category==='merfolk'&&pose.requiresLegs)return '人魚の尾では脚を使うこの姿勢は選べません。';if(pose.requiresFeature&&!feature(o,pose.requiresFeature))return ({cape:'マント',coat:'コート',collar:'襟',sleeves:'袖',skirt:'スカート',backDecoration:'装飾'})[pose.requiresFeature]+'のある衣装で選べます。衣装は自動追加しません。';return '';}
function seats(pose){return pose&&pose.support?(supports[pose.support]||[]):[];}
function update(o,key,value){var p=editable(o.presentation),pose;if(key==='poseId'&&(pose=U.byId(P.poseChoices,value))&&reason(o,pose))throw Error(reason(o,pose));p[key]=value||null;if(key==='poseId'){var set=U.byId(C.data.presentationLegacyMap,value);if(set&&set.kind==='set'){p.distanceId=set.distanceId;p.angleId=set.angleId;}}pose=U.byId(P.poseChoices,p.poseId);var warning='';if(p.seat&&seats(pose).indexOf(p.seat)<0){p.seat=null;warning='この姿勢に合わない支える場所を解除しました。必要なら選び直してください。';}o.presentation=C.presentation.normalize(p);return warning;}
function fragments(o){var p=o.presentation,pose=U.byId(P.poseChoices,p.poseId),short=[],detailed=[];
function add(s,d){if(s){short.push(s);detailed.push(d||s);}}
var subject=U.byId(P.subjects,p.subject);if(subject)add(subject.shortPrompt,subject.detailedPrompt);
if(pose&&!reason(o,pose)){add(pose.shortPrompt,pose.detailedPrompt);var allowed=seats(pose),seatId=allowed.includes(p.seat)?p.seat:allowed[0],seat=U.byId(P.seats,seatId);if(seat){var text=seat.shortPrompt;if(pose.support==='lie'||pose.support==='chaise'){if(seat.id==='bed')text='the surface of a neatly made bed';if(seat.id==='floor')text='the floor';}add('supported by '+text,'The body is supported by '+text);}if(o.garment.category==='merfolk')add('with the tail arranged naturally','Arrange the tail naturally along the supporting surface');}
[P.distances,P.angles,P.poseMoods].forEach(function(list,i){var id=[p.distanceId,p.angleId,p.poseMood][i],x=U.byId(list,id);if(x)add(x.shortPrompt.replace(/^Use /,''),x.detailedPrompt.replace(/^Use /,''));});return {short:short,detailed:detailed};}
C.presentation.blocks=function(o){if(!o.presentation||o.presentation.layoutVersion!==1)return baseBlocks(o);var clean=U.clone(o);clean.presentation=Object.assign({},baseNormalize(o.presentation),{preset:null,focus:null,poseAssist:null,poseMood:null,subject:null});if(clean.presentation.compositionAssist!=='plain_bg')clean.presentation.compositionAssist=null;var result=baseBlocks(clean);if(o.output.includePresentation){var f=fragments(o);result.presentation.short=f.short.concat(result.presentation.short);result.presentation.detailed=f.detailed.concat(result.presentation.detailed);}return result;};
function summary(o){var p=o.presentation,items=[];if(p.layoutVersion===1){[[P.poseChoices,p.poseId],[P.distances,p.distanceId],[P.angles,p.angleId],[P.poseMoods,p.poseMood]].forEach(function(pair){var x=U.byId(pair[0],pair[1]);if(x)items.push(x.labelJa);});}else{var x=U.byId(P.presets,p.preset);if(x)items.push(x.labelJa);else if(p.poseAssist){x=U.byId(C.data.poseAssist,p.poseAssist);if(x)items.push(x.labelJa);}}return items.length?items.join('・'):'未指定';}
function link(){var box=E('div',{class:'card stack'});box.appendChild(E('a',{class:'btn',href:'#/presentation',text:'ポーズ・構図を選ぶ'}));box.appendChild(E('p',{class:'p p--note',text:'ポーズ：'+summary(C.state.outfit)+(C.state.outfit.output.includePresentation?'':'（現在は出力しません）')}));return box;}
var tab='pose',category='',query='';
function view(){var host=E('section',{class:'screen discovery'}),message='';
function button(text,fn,attrs){return E('button',Object.assign({class:'btn',type:'button',text:text,onclick:fn},attrs));}
function change(key,value,id){message=update(C.state.outfit,key,value);C.state.touch();redraw(id);}
function redraw(id){var y=g.scrollY;draw();if(id){var n=host.querySelector('[data-choice="'+id+'"]');if(n)n.focus({preventScroll:true});}g.scrollTo(0,y);}
function draw(){var o=C.state.outfit,p=editable(o.presentation),pose=U.byId(P.poseChoices,p.poseId);host.replaceChildren(E('a',{href:'#/workshop',class:'back-btn',text:'← 衣装を編集する'}),E('h1',{class:'page-title',text:'ポーズ・構図を選ぶ'}),E('p',{class:'p',id:'pose-summary',text:summary(o)}));var status=E('p',{role:'status',text:message||(!o.output.includePresentation?'ポーズは選択済みでも、現在は出力しません。':'選んだポーズ・構図を出力します。')});host.appendChild(status);
var clear=E('div',{class:'chips'});[['poseId','ポーズ'],['distanceId','距離'],['angleId','角度'],['poseMood','雰囲気']].forEach(function(r){clear.appendChild(button(r[1]+'を解除',function(){change(r[0],null,'clear-'+r[0]);},{'data-choice':'clear-'+r[0]}));});host.appendChild(clear);
var bad=reason(o,pose);if(bad)host.appendChild(E('p',{class:'p p--warn',role:'status',text:bad+' この姿勢は出力しません。'}));
host.appendChild(button('ポーズを出力に含める：'+(o.output.includePresentation?'ON':'OFF'),function(){if(o.output.includePresentation)C.presentation.setScope(o,'outfit');else C.presentation.setScope(o,o.output.includeBackground||o.output.includeRendering?'all':'pose');C.state.touch();redraw('include');},{'aria-pressed':String(o.output.includePresentation),'data-choice':'include'}));
var allowed=seats(pose);if(allowed.length){var s=E('select',{id:'pose-seat',class:'cf-select'});s.appendChild(E('option',{value:'',text:'姿勢の標準：'+U.byId(P.seats,allowed[0]).labelJa}));allowed.forEach(function(id){s.appendChild(E('option',{value:id,text:U.byId(P.seats,id).labelJa}));});s.value=allowed.includes(p.seat)?p.seat:'';s.addEventListener('change',function(){change('seat',s.value,null);});host.appendChild(E('label',{for:'pose-seat',text:'支える場所（姿勢に合うものだけ表示）'}));host.appendChild(s);host.appendChild(button('支える場所を標準に戻す',function(){change('seat',null,null);}));}
var tabs=E('div',{class:'tabs','aria-label':'ポーズの設定領域'});[['pose','ポーズ'],['composition','構図'],['mood','雰囲気']].forEach(function(r){tabs.appendChild(button(r[1],function(){tab=r[0];redraw('tab-'+r[0]);},{'aria-pressed':String(tab===r[0]),'data-choice':'tab-'+r[0]}));});host.appendChild(tabs);
if(tab==='pose'){var search=E('input',{id:'pose-search',type:'search',class:'name-input'});search.value=query;host.appendChild(E('label',{for:'pose-search',text:'名前・説明でポーズを検索'}));host.appendChild(search);var select=E('select',{id:'pose-category',class:'cf-select'});select.appendChild(E('option',{value:'',text:'すべて'}));C.data.poseCategories.forEach(function(c){select.appendChild(E('option',{value:c.id,text:c.labelJa}));});select.value=category;host.appendChild(E('label',{for:'pose-category',text:'ポーズ分類'}));host.appendChild(select);var grid=E('div',{class:'discovery-grid'});host.appendChild(grid);
function results(){grid.replaceChildren();var q=C.presetCatalog.normalizeSearch(query),list=P.poseChoices.filter(function(x){return (!category||x.categoryId===category)&&C.presetCatalog.normalizeSearch([x.labelJa,x.noteJa].concat(x.searchAliases).join(' ')).includes(q);});if(!list.length)grid.appendChild(E('p',{text:'一致するポーズがありません。検索や分類を解除してください。'}));list.forEach(function(x){var on=p.poseId===x.id,r=reason(o,x),b=button('',function(){change('poseId',x.id,x.id);},{class:'card card--tap'+(on?' is-selected':''),'aria-pressed':String(on),'aria-disabled':r?'true':null,disabled:!!r,'data-choice':x.id});b.appendChild(E('strong',{text:(on?'✓ ':'')+x.labelJa}));b.appendChild(E('p',{class:'p',text:x.noteJa}));if(x.kind==='set')b.appendChild(E('p',{class:'p p--note',text:'旧セット（距離・角度は後から変更できます）'}));if(r)b.appendChild(E('p',{class:'p p--warn',text:r}));grid.appendChild(b);});}
search.addEventListener('input',function(){query=search.value;results();});select.addEventListener('change',function(){category=select.value;results();});host.appendChild(button('検索・分類を解除',function(){query=category='';search.value=select.value='';results();}));results();
}else{var sections=tab==='composition'?[[P.distances,'distanceId','距離'],[P.angles,'angleId','角度']]:[[P.poseMoods,'poseMood','雰囲気']];sections.forEach(function(section){host.appendChild(E('h2',{text:section[2]}));var row=E('div',{class:'discovery-grid'});[{id:null,labelJa:'未指定'}].concat(section[0]).forEach(function(x){var on=p[section[1]]===x.id,id=section[1]+'-'+(x.id||'none');row.appendChild(button((on?'✓ ':'')+x.labelJa,function(){change(section[1],x.id,id);},{'aria-pressed':String(on),'data-choice':id,class:'btn'+(on?' is-selected':'')}));});host.appendChild(row);});}
host.appendChild(E('a',{href:'#/output',class:'btn btn--primary',text:'プロンプトを見る'}));}
draw();return host;}
C.presentationChoices={editable:editable,update:update,reason:reason,seats:seats,summary:summary,link:link,view:view};C.routes['/presentation']=view;
})(window);
