(function(g){
  'use strict';var C=g.CPW,F=C.data.conceptFashion,E=C.conceptFashion;
  function test(n,f){C.tests.push({name:'5F: '+n,fn:function(){var prefs=C.uiPrefs.snapshot(),raw=null;try{raw=g.localStorage.getItem(C.uiPrefs.key);}catch(e){}try{f();}finally{C.uiPrefs.set('workshop',prefs.workshopLevel);C.uiPrefs.set('concept',prefs.conceptLevel);try{if(raw===null)g.localStorage.removeItem(C.uiPrefs.key);else g.localStorage.setItem(C.uiPrefs.key,raw);}catch(e){}}}});}function assert(v,m){if(!v)throw Error(m||'Phase 5F assertion');}
  F.inspired.ids.forEach(function(id){test('discover and translate '+id,function(){var m=C.util.byId(F.motifs,id),s=E.normalizeSelection({}),raw=JSON.stringify(s),r=C.conceptSearch.choose(s,id);assert(JSON.stringify(s)===raw);assert(r.motifId===id&&r.categoryId===m.category);assert(C.conceptSearch.search(m.labelJa,m.category,false).some(function(x){return x.id===id;}));var p=m.recommended;assert(p.colors.length&&p.materials.length&&p.decorations.length&&Object.keys(p.parts).length);var cs=E.buildCandidates(r,{seed:53});assert(cs.length===3);cs.forEach(function(c){assert(c.motifContributions[0].paths.length>=2);assert(!/searchKeywords|featured/.test(JSON.stringify(c.outfit)));});});});
  test('160 new authored motifs and 35 objects',function(){assert(F.inspired.ids.length===160);assert(F.motifs.length+F.attires.length===471);assert(F.motifs.filter(function(m){return m.category==='object';}).length===35);});
  test('search is local, bounded, case insensitive and category ranked',function(){assert(C.conceptSearch.search('GLASS','object',true)[0].category==='object');assert(C.conceptSearch.search('xyz-no-such-motif','object',true).length===0);assert(C.conceptSearch.search('','object',true).length===0);assert(C.conceptSearch.search('inspired',null,true).length<=30);assert(C.conceptSearch.search('くらげ','living',true).some(function(m){return m.id==='jellyfish';}));});
  test('traditional search sets matching region and attire',function(){var s=C.conceptSearch.choose(E.normalizeSelection({}),'qipao');assert(s.categoryId==='traditional'&&s.traditional.attireId==='qipao'&&s.traditional.regionId);});
  test('levels never change outfit, dirty, timestamps or generated text',function(){var o=JSON.stringify(C.state.outfit),dirty=C.state.dirty,text=C.generator.detailed(C.state.outfit);['simple','advanced','simple'].forEach(function(level){C.uiPrefs.set('workshop',level);C.uiPrefs.set('concept',level);assert(JSON.stringify(C.state.outfit)===o&&C.state.dirty===dirty);assert(C.generator.detailed(C.state.outfit)===text);});});
  test('levels are independent and invalid values ignored',function(){C.uiPrefs.set('workshop','advanced');C.uiPrefs.set('concept','simple');C.uiPrefs.set('concept','broken');assert(C.uiPrefs.get('workshop')==='advanced'&&C.uiPrefs.get('concept')==='simple');C.uiPrefs.set('workshop','simple');});
  test('empty defaults do not claim hidden configuration',function(){assert(C.uiComplexity.hiddenSummary(C.schema.createOutfit(),'workshop').count===0);assert(C.uiComplexity.hiddenSummary(C.schema.emptyInspiration(),'concept').count===0);});
  test('hidden summary retains secondary and all advanced draft axes',function(){var s=E.normalizeSelection({secondary:{categoryId:'object',motifId:'hourglass'},directions:['dark','elegant'],context:{roleId:'knight'},exclusions:['no_wings'],designLanguages:['linear']});var raw=JSON.stringify(s),h=C.uiComplexity.hiddenSummary(s,'concept');assert(h.groups.length===4&&h.count===5);assert(JSON.stringify(s)===raw);});
  C.data.garmentCategories.forEach(function(cat){test('simple required slots '+cat.id,function(){var o=C.schema.normalize({garment:{category:cat.id}});(cat.requiredSlots||[]).forEach(function(id){assert(C.uiComplexity.isSimpleField('parts.'+id,o),id);});});});
  test('all new motifs are reachable through seeded random selection',function(){var seen={};for(var i=0;i<15000;i++){var s=E.randomSelection('all',i);seen[s.motifId]=true;}F.inspired.ids.forEach(function(id){assert(seen[id],id);});});
  F.randomProfiles.forEach(function(p){test('expanded random profile '+p.id+' remains deterministic',function(){for(var seed=1;seed<=5;seed++){var a=E.randomSelection(p.id,seed),b=E.randomSelection(p.id,seed);assert(JSON.stringify(a)===JSON.stringify(b));var cs=E.buildCandidates(a,{seed:seed});assert(cs.length===3);assert(cs.map(function(c){return c.strategy;}).join(',')==='readable,wearable,experimental');}});});
  ['stained_glass','jellyfish','hourglass','perfume_bottle','peacock','opal'].forEach(function(id){[1,7,19,73,211].forEach(function(seed){['new','preserve'].forEach(function(mode){test(id+' seed '+seed+' '+mode+' round trip all strategies',function(){var m=C.util.byId(F.motifs,id),current=C.schema.normalize({garment:{category:'merfolk',subtype:'sea_silk_mermaid_outfit'},palette:{primary:'jet_black'},condition:{items:[{type:'repaired'}]},output:{customTags:'Exact,(Tag:1.2)'}}),raw=JSON.stringify(current),cs=E.buildCandidates({categoryId:m.category,motifId:id},{seed:seed,mode:mode,currentOutfit:current});assert(cs.length===3);cs.forEach(function(c){var o=C.schema.normalize(JSON.parse(C.store.exportOutfit(c.outfit)).outfit);assert(JSON.stringify(o.concept.inspiration)===JSON.stringify(c.outfit.concept.inspiration));assert(C.generator.detailed(o)===C.generator.detailed(c.outfit));if(mode==='preserve'){assert(o.garment.category==='merfolk'&&o.palette.primary==='jet_black'&&o.output.customTags===current.output.customTags);assert(o.condition.items[0].type==='repaired');var text=C.generator.detailed(o).replace(/no human legs|no feet|replacing separate human legs and feet/g,'');assert(!/\b(trousers|pants|shoes|boots|legs|feet)\b/i.test(text));}['simple','advanced'].forEach(function(level){C.uiPrefs.set('workshop',level);C.uiPrefs.set('concept',level);var before=JSON.stringify(o);C.uiComplexity.hiddenSummary(o,'workshop');C.uiComplexity.hiddenSummary(o,'concept');assert(JSON.stringify(o)===before);});});assert(JSON.stringify(current)===raw);});});});});
  [['jet_black','charcoal_gray'],['ink_black','pearl_gray'],['scarlet','wine_red'],['cobalt_blue','sky_blue']].forEach(function(pair){['simple','advanced'].forEach(function(level){['short','detailed'].forEach(function(format){test('safe color scheme '+pair.join('/')+' '+level+' '+format,function(){C.uiPrefs.set('workshop',level);var o=C.schema.normalize({garment:{category:'dress',subtype:'cocktail_dress'},palette:{primary:pair[0],secondary:pair[1],scheme:'monochrome'}}),text=C.generator[format](o);assert(!/\b(monochrome|grayscale)\b/i.test(text));pair.forEach(function(id){assert(text.indexOf(C.util.byId(C.data.colors,id).promptEn)>=0);});assert(o.palette.scheme==='monochrome');});});});});
  test('recorded advanced inspiration remains visible in workshop summary',function(){var o=C.schema.normalize({concept:{inspiration:{secondary:{categoryId:'object',motifId:'hourglass'}}}});assert(C.uiComplexity.hiddenSummary(o,'workshop').groups.some(function(x){return x.id==='inspiration';}));});
  ['stained_glass','jellyfish','hourglass','perfume_bottle','peacock','opal'].forEach(function(id){test('acceptance visual translation '+id,function(){var m=C.util.byId(F.motifs,id),cs=E.buildCandidates({categoryId:m.category,motifId:id,baseId:'dress'},{seed:11});cs.forEach(function(c){assert(c.outfit.palette.primary&&c.outfit.materials.primary&&c.outfit.parts.construction_detail&&c.outfit.decorations.items.length);});var o=cs[0].outfit;if(id==='hourglass')assert(o.silhouette.waist==='cinched_waist'&&o.silhouette.lowerVolume==='bell_volume'&&o.silhouette.symmetry==='symmetrical');if(id==='perfume_bottle')assert(o.silhouette.fit==='cocoon_fit'&&o.materials.primary==='translucent_film'&&o.decorations.items.some(function(d){return d.type==='ornamental_clasps';}));if(id==='jellyfish')assert(o.silhouette.fit==='draped'&&o.materials.secondary==='translucent_film');if(id==='peacock')assert(o.materials.secondary==='iridescent_fabric'&&o.palette.primary==='peacock_blue');if(id==='opal')assert(o.materials.primary==='iridescent_fabric'&&o.palette.primary==='opal_white');});});
})(window);
