/* Phase 5D: behavior and source-vocabulary regressions. */
(function (global) {
  'use strict';
  var C=global.CPW,D=C.data,F=D.conceptFashion,U=C.util;
  function assert(v,m){if(!v)throw new Error(m||'Phase 5D assertion');}
  function test(n,f){C.tests.push({name:'5D: '+n,fn:f});}
  Object.keys(F).filter(function(k){return Array.isArray(F[k]);}).forEach(function(k){
    test(k+' vocabulary IDs and labels',function(){var ids={};F[k].forEach(function(o){assert(/^[a-z][a-z0-9_]*$/.test(o.id),o.id);assert(!ids[o.id],o.id);ids[o.id]=true;assert(o.labelJa&&o.shortPrompt,o.id);});});
  });
  test('source categories complete',function(){assert(F.categories.length===10);});
  test('all 112 source motifs including 72 extended foods',function(){assert(F.motifs.length===112);assert(F.motifs.filter(function(m){return m.category==='food';}).length===72);});
  test('all traditional attires retained',function(){assert(F.attires.length===14);});
  test('all 15 idol and 8 botanical shapes retained',function(){assert(F.idolStyles.length===15&&F.artNouveauShapes.length===8);});
  test('motif category and food group references',function(){F.motifs.forEach(function(m){assert(U.byId(F.categories,m.category),m.id);if(m.category==='food')assert(U.byId(F.foodGroups,m.groupId),m.id);});});
  function checkProfile(p){
    ['colors','materials','decorations','styles','garments','motifs','patterns'].forEach(function(k){(p[k]||[]).forEach(function(id){assert(U.byId(D[k],id),k+': '+id);});});
    Object.keys(p.silhouette||{}).forEach(function(k){p.silhouette[k].forEach(function(id){assert(U.byId(D.silhouette[k],id),'silhouette '+k+': '+id);});});
    Object.keys(p.parts||{}).forEach(function(k){var slot=U.byId(D.partSlots,k);assert(slot,k);p.parts[k].forEach(function(id){assert(U.byId(slot.options,id),k+': '+id);});});
    Object.keys(p.specialParts||{}).forEach(function(k){var slot=U.byId(D.specialParts.slots,k);assert(slot,k);assert(p.specialParts[k][slot.requiredAxis],k+' required axis');Object.keys(p.specialParts[k]).forEach(function(a){assert(U.byId(C.schema.axisOf(slot,a).options,p.specialParts[k][a]),k+'.'+a);});});
  }
  F.categories.forEach(function(cat){test(cat.id+' explicit mappings exist and target real IDs',function(){F.motifs.filter(function(m){return m.category===cat.id;}).forEach(function(m){assert(F.mappings.motifs[m.id],m.id);checkProfile(F.mappings.motifs[m.id]);});if(cat.id==='traditional')F.attires.forEach(function(a){checkProfile(F.mappings.traditional[a.id]);});});});
  F.bases.forEach(function(b){test('base '+b.id+' uses existing garment pool',function(){assert(F.mappings.bases[b.id].length);F.mappings.bases[b.id].forEach(function(id){assert(U.byId(D.garments,id),id);});});});
  test('direction mappings use existing styles',function(){F.directions.forEach(function(d){assert(F.mappings.directions[d.id]);F.mappings.directions[d.id].forEach(function(id){assert(U.byId(D.styles,id),id);});});});
  var sample={categoryId:'nature',motifId:'aurora',baseId:'gown',strengthId:'bold'};
  test('candidate full object is seed reproducible',function(){assert(JSON.stringify(C.conceptFashion.buildCandidates(sample,{seed:7}))===JSON.stringify(C.conceptFashion.buildCandidates(sample,{seed:7})));});
  test('preview does not mutate source, state, or selection',function(){var before=JSON.stringify(C.state.outfit),s=U.clone(sample),raw=JSON.stringify(s);var r=C.conceptFashion.buildCandidates(s,{seed:12,currentOutfit:C.state.outfit,mode:'preserve'});assert(r.length===3);assert(before===JSON.stringify(C.state.outfit));assert(raw===JSON.stringify(s));r[0].outfit.palette.primary='jet_black';assert(before===JSON.stringify(C.state.outfit));});
  test('unknown custom concept never guesses colors/materials',function(){C.conceptFashion.buildCandidates({customMotif:'忘れられた約束',baseId:'dress',directions:['graceful']},{seed:7}).forEach(function(c){assert(c.outfit.palette.primary===null&&c.outfit.materials.primary===null);assert(c.outfit.output.customTags==='');});});
  test('candidate reasons and warnings use distinct fields',function(){var r=C.conceptFashion.buildCandidates(sample,{seed:8});assert(r.length===3);r.forEach(function(c){assert(c.reasons.length);assert(JSON.stringify(c.warnings)===JSON.stringify(C.advisor.check(c.outfit)));assert(c.reasons.every(function(x){return x.reasonJa&&x.target;}));});});
  test('preserve mode protects explicit garment palette and tags',function(){var o=C.schema.normalize({garment:{subtype:'reverse_bunny_suit',category:'lingerie'},palette:{primary:'jet_black'},output:{customTags:'User, (exact:1.2)'}});var before=JSON.stringify(o);C.conceptFashion.buildCandidates(sample,{seed:7,currentOutfit:o,mode:'preserve'}).forEach(function(c){assert(c.outfit.garment.subtype===o.garment.subtype);assert(c.outfit.palette.primary==='jet_black');assert(c.outfit.output.customTags===o.output.customTags);});assert(JSON.stringify(o)===before);});
  test('strength controls applied structural axes',function(){var subtle=C.conceptFashion.buildCandidates(Object.assign({},sample,{strengthId:'subtle'}),{seed:4})[0],bold=C.conceptFashion.buildCandidates(sample,{seed:4})[0];assert(bold.appliedPaths.length>subtle.appliedPaths.length);});
  test('selection limits and unknown IDs',function(){var s=C.conceptFashion.normalizeSelection({directions:['elegant','cute','dark','bad'],placements:F.placements.map(function(x){return x.id;}),baseId:'unknown',exposure:9});assert(s.directions.length===2&&s.placements.length===4&&s.baseId===null&&s.exposure===null);});
  test('schema version 0.5',function(){assert(C.SCHEMA_VERSION==='0.5');});
  ['0.1','0.2','0.3','0.4'].forEach(function(v){test(v+' migration leaves inspiration empty and tags exact',function(){var old=C.schema.createOutfit();old.version=v;old.output.customTags='  custom, (tags:1.4)  ';var r=C.schema.migrate(old);assert(r.ok&&r.outfit.version==='0.5');assert(JSON.stringify(r.outfit.concept.inspiration)===JSON.stringify(C.conceptFashion.normalizeSelection({})));assert(r.outfit.output.customTags===old.output.customTags);assert(!r.outfit.output.includeBackground&&!r.outfit.output.includeRendering);});});
  test('all 32 Phase 5C main preset outputs remain byte-identical',function(){assert(C.phase5dBaseline.length===32);C.phase5dBaseline.forEach(function(f){var o=C.schema.migrate(f.outfit).outfit;assert(C.generator.short(o)===f.short,f.id+' short');assert(C.generator.detailed(o)===f.detailed,f.id+' detailed');});});
  function rich(){var o=C.conceptFashion.buildCandidates(sample,{seed:8})[0].outfit;o.output.customTags='  exact,(tag:1.3), <x>  ';o.styling.items=['asymmetrically_worn'];o.condition.items=[{type:D.conditions[0].id,severity:'moderate',extent:'localized',placements:[]}];o.specialParts.wings={type:'angel_wings',size:'wing_large'};o.garment.layers.outer=['cape_coat'];return C.schema.normalize(o);}
  function retained(a,b){['concept','presentation','styling','condition','specialParts','garment','output'].forEach(function(k){assert(JSON.stringify(a[k])===JSON.stringify(b[k]),k+' changed');});}
  test('0.5 normalized JSON roundtrip retains extended design',function(){var o=rich();retained(o,C.schema.normalize(JSON.parse(JSON.stringify(o))));});
  function withStore(fn){var read=C.store._read,write=C.store._write,m={};C.store._read=function(k,d){return m[k]?U.clone(m[k]):d;};C.store._write=function(k,v){m[k]=U.clone(v);return true;};try{fn();}finally{C.store._read=read;C.store._write=write;}}
  test('draft save reload retains concept and tags',function(){withStore(function(){var o=rich();C.store.saveDraft(o);retained(o,C.store.loadDraft());});});
  test('library save reload retains extended design',function(){withStore(function(){var o=rich(),saved=C.store.saveOutfit(o);retained(o,C.store.getOutfit(saved.id));});});
  test('duplicate retains extended design with independent identity',function(){withStore(function(){var o=rich();C.store.saveOutfit(o);var copy=C.store.duplicateOutfit(o.id);assert(copy.id!==o.id);retained(o,copy);});});
  test('single JSON export import retains all extended fields',function(){withStore(function(){var o=rich(),r=C.store.importJSON(C.store.exportOutfit(o));assert(r.ok);retained(o,C.store.listOutfits()[0]);});});
  test('library JSON export import retains all extended fields',function(){withStore(function(){var o=rich();C.store.saveOutfit(o);var r=C.store.importJSON(C.store.exportAll());assert(r.ok);C.store.listOutfits().forEach(function(x){retained(o,x);});});});
  test('unknown inspiration IDs are ignored',function(){var o=C.schema.normalize({concept:{inspiration:{categoryId:'bad',motifId:'bad',directions:['bad'],traditional:{attireId:'bad'}}}});assert(o.concept.inspiration.motifId===null&&o.concept.inspiration.directions.length===0);});
  function candidates(s){return C.conceptFashion.buildCandidates(s,{seed:5});}
  function first(s){var a=candidates(s);assert(a.length===3,'expected three candidates');return a[0].outfit;}
  test('A first love structured colors, soft cloth, pearls',function(){var o=first({categoryId:'concept',motifId:'first_love',directions:['graceful'],baseId:'dress'});assert(o.palette.primary==='blush_pink'&&o.materials.primary==='organza');assert(o.decorations.items.some(function(x){return x.type==='pearl_details';}));});
  test('B aurora iridescence and drape',function(){var o=first(sample);assert(o.materials.primary==='iridescent_fabric'&&o.parts.construction_detail==='draped_panels');});
  test('C crystal dragon activates required special axes',function(){var o=first({categoryId:'fantasy',motifId:'crystal_dragon',baseId:'armor'});assert(o.specialParts.horns.type==='horn_crystal'&&o.specialParts.wings.type==='dragon_wings');assert(C.schema.activeSpecialParts(o).length===2);});
  test('D Art Nouveau no-slit is not overridden by exposure',function(){var o=first({categoryId:'art',motifId:'art_nouveau',artNouveauShapeId:'no_slit',exposure:5});assert(o.parts.hem==='straight_hem');assert(!/slit/i.test(C.generator.detailed(o)));});
  var qipao={categoryId:'traditional',traditional:{attireId:'qipao',treatmentId:'traditional',qipaoNecklineId:'classic',qipaoLengthId:'long',qipaoSlitId:'none'}};
  test('E traditional qipao canonical collar length and closed hem',function(){var o=first(qipao);assert(o.garment.subtype==='qipao'&&o.parts.collar==='mandarin_collar'&&o.silhouette.length==='ankle_length'&&o.parts.hem==='straight_hem');assert(!/slit/i.test(C.generator.detailed(o)));});
  test('F traditional hanbok has no automatic Chinese fastenings',function(){var o=first({categoryId:'traditional',traditional:{attireId:'hanbok',treatmentId:'traditional'},exposure:5});assert(o.garment.subtype==='hanbok'&&!o.parts.cutout);assert(!/hanfu|qipao|frog closure|mandarin collar/i.test(C.generator.detailed(o)));});
  test('G cream soda is abstracted and no literal food is inserted',function(){var o=first({categoryId:'food',foodGroupId:'drinks',motifId:'cream_soda',placements:['palette','materials','ornament']});assert(o.palette.primary==='mint'&&o.palette.secondary==='pearl_white');assert(o.materials.primary==='translucent_film');assert(!/tray|drink on|glass of/.test(C.generator.detailed(o)));});
  test('H custom motif is preserved without customTags pollution',function(){var o=first({customMotif:'忘れられた約束',baseId:'dress',directions:['graceful']});assert(o.concept.inspiration.customMotif==='忘れられた約束'&&o.output.customTags==='');assert(o.materials.primary===null);});
  test('I unisex idol has structured tailoring without subject',function(){var o=first({categoryId:'stage',motifId:'idol',directions:['futuristic'],idolStyleId:'unisex'});assert(o.garment.category==='uniform'&&o.parts.bottoms==='wide_trousers'&&o.presentation.subject===null);assert(!/1girl|1boy|\bman\b|\bwoman\b/.test(C.generator.detailed(o)));});
  test('J mermaid tale includes a merfolk and a human outfit',function(){var cs=candidates({categoryId:'myth',motifId:'mermaid_tale'});assert(cs.some(function(c){return c.outfit.garment.category==='merfolk';}));assert(cs.some(function(c){return c.outfit.garment.category==='dress';}));cs.filter(function(c){return c.outfit.garment.category==='merfolk';}).forEach(function(c){assert(!/trousers|shoes|stockings/.test(C.generator.short(c.outfit)));});});
  test('K coverage changes construction without body narration',function(){var a=first(Object.assign({},sample,{exposure:0})),b=first(Object.assign({},sample,{exposure:5}));assert(JSON.stringify(a.parts)!==JSON.stringify(b.parts));assert(!/breasts|cleavage|erotic|nude/.test(C.generator.detailed(b)));});
  test('L legacy reverse bunny output stays unchanged',function(){var f=C.phase5dBaseline.find(function(f){return f.outfit.garment.subtype==='reverse_bunny_suit';});assert(f);assert(C.generator.detailed(C.schema.migrate(f.outfit).outfit)===f.detailed);});
  F.attires.forEach(function(a){test('traditional '+a.id+' stays identifiable at maximum exposure',function(){var o=first({categoryId:'traditional',traditional:{attireId:a.id,treatmentId:'traditional'},exposure:5});assert(o.garment.subtype===a.id,a.id);assert(!o.parts.cutout,a.id+' cutout');assert(!/mini length|plunging neckline/.test(C.generator.short(o)),a.id);});});
  F.idolStyles.forEach(function(v){test('idol variant '+v.id+' maps into editable structure',function(){var o=first({categoryId:'stage',motifId:'idol',idolStyleId:v.id});assert(o.presentation.subject===null);assert(C.conceptFashion.detailProfiles.idol[v.id]);assert(!C.advisor.check(o).some(function(w){return w.severity==='hard';}));});});
  F.artNouveauShapes.forEach(function(v){test('Art Nouveau '+v.id+' honors shape without automatic high slit',function(){var o=first({categoryId:'art',motifId:'art_nouveau',artNouveauShapeId:v.id});assert(!/high.side.slit/.test(C.generator.detailed(o)));var p=C.conceptFashion.detailProfiles.artNouveau[v.id];if(p.silhouette)assert(o.silhouette.length===p.silhouette.length);if(p.garment)assert(o.garment.subtype===p.garment);});});
  F.qipaoNecklines.forEach(function(v){test('qipao '+v.id+' neckline uses slots',function(){var o=first({categoryId:'traditional',traditional:{attireId:'qipao',treatmentId:'modern',qipaoNecklineId:v.id}}),p=C.conceptFashion.detailProfiles.qipaoNeckline[v.id];Object.keys(p.parts).forEach(function(k){assert(JSON.stringify(o.parts[k])===JSON.stringify(C.schema.normalizePartValue(U.byId(D.partSlots,k),p.parts[k])),k);});});});
  F.foodGroups.forEach(function(g){test('food group '+g.id+' all candidates retain valid abstractions',function(){F.motifs.filter(function(m){return m.groupId===g.id;}).forEach(function(m){var o=first({categoryId:'food',foodGroupId:g.id,motifId:m.id});assert(o.output.customTags==='');assert(U.byId(D.colors,o.palette.primary));assert(U.byId(D.materials,o.materials.primary));});});});
  Object.keys(D.presentation).forEach(function(k){test('presentation '+k+' unique valid IDs',function(){var seen={};D.presentation[k].forEach(function(x){assert(/^[a-z][a-z0-9_]*$/.test(x.id)&&!seen[x.id],x.id);seen[x.id]=true;assert(x.labelJa&&(x.shortPrompt||x.id==='none'),x.id);});});});
  function presented(){var o=rich();o.presentation={focus:'full_outfit',poseAssist:'standing',compositionAssist:'plain_bg',preset:'seated',poseMood:'refined',seat:'armchair',background:'theme',subject:null,rendering:{enabled:true,paint:'watercolor',finish:'glossy',line:'delicate'}};return C.schema.normalize(o);}
  ['outfit','pose','all'].forEach(function(scope){test('M '+scope+' has strict block boundaries',function(){var o=presented();C.presentation.setScope(o,scope);var b=C.generator.blocks(o);assert((b.presentation.short.length>0)===(scope!=='outfit'));assert((b.background.short.length>0)===(scope==='all'));assert((b.rendering.short.length>0)===(scope==='all'));var text=C.generator.detailed(o);if(scope==='outfit')assert(!/armchair|watercolor|background|standing pose|seated pose/.test(text));if(scope==='pose')assert(!/watercolor|background|environment/.test(text));});});
  test('N schema 0.4 presentation defaults preserve existing output',function(){C.phase5dBaseline.forEach(function(f){var o=C.schema.migrate(f.outfit).outfit;assert(o.presentation.subject===null&&!o.presentation.rendering.enabled);assert(C.generator.short(o)===f.short);});});
  test('O generating three previews does not change draft or saved library',function(){withStore(function(){var o=rich();C.store.saveDraft(o);C.store.saveOutfit(o);var d=JSON.stringify(C.store.loadDraft()),lib=C.store.exportAll();first(sample);assert(d===JSON.stringify(C.store.loadDraft()));assert(JSON.stringify(JSON.parse(lib).outfits)===JSON.stringify(JSON.parse(C.store.exportAll()).outfits));});});
  test('P inspiration presentation styling condition customTags full roundtrip',function(){withStore(function(){var o=presented();C.presentation.setScope(o,'all');C.store.saveOutfit(o);var d=C.store.duplicateOutfit(o.id);retained(o,d);C.store.importJSON(C.store.exportAll());C.store.listOutfits().forEach(function(x){retained(o,x);});});});
  test('Q no automatic subject even for bunny maid or suits',function(){['classic_bunny_suit','reverse_bunny_suit','maid_dress','business_suit'].forEach(function(id){var o=presented(),g=U.byId(D.garments,id);o.garment={category:g.category,subtype:id};C.presentation.setScope(o,'all');assert(!/\b(?:1girl|1boy|man|woman)\b/.test(C.generator.detailed(o)));});});
  test('R seat supports figure and suppresses dormant standing pose',function(){var o=presented();C.presentation.setScope(o,'pose');var t=C.generator.detailed(o);assert(/supported.*seated.*armchair/.test(t));assert(!/standing pose/.test(t));});
  D.presentation.presets.forEach(function(p){test('presentation '+p.id+' scope and seat behavior',function(){var o=presented();o.presentation.preset=p.id;C.presentation.setScope(o,'pose');var b=C.generator.blocks(o);assert(b.presentation.short.length);if(!p.seated)assert(!/armchair/.test(b.presentation.short.join(' ')));assert(b.background.short.length===0&&b.rendering.short.length===0);});});
  test('seat cannot contradict sofa/chair preset when explicit seat selected',function(){var o=presented();o.presentation.preset='sofa_sit';C.presentation.setScope(o,'pose');var t=C.generator.blocks(o).presentation.detailed.join(' ');assert(/armchair/.test(t)&&!/sofa/.test(t));});
  test('all subject choices are opt-in and outfit-only suppresses them',function(){D.presentation.subjects.forEach(function(s){var o=presented();o.presentation.subject=s.id;C.presentation.setScope(o,'all');assert(C.generator.blocks(o).presentation.short.indexOf(s.shortPrompt)>=0);C.presentation.setScope(o,'outfit');assert(C.generator.blocks(o).presentation.short.length===0);});});
  test('rendering glossy is separate from material surface',function(){var o=presented();o.materials.surface='matte';o.presentation.rendering.paint='glossy';C.presentation.setScope(o,'all');var b=C.generator.blocks(o);assert(b.rendering.short.indexOf('glossy rendering')>=0);assert(o.materials.surface==='matte');});
  test('rendering enable gate',function(){var o=presented();C.presentation.setScope(o,'all');o.presentation.rendering.enabled=false;assert(C.generator.blocks(o).rendering.short.length===0);});
  test('unknown presentation IDs safely drop',function(){var o=C.schema.normalize({presentation:{preset:'bad',seat:'bad',subject:'bad',rendering:{enabled:true,paint:'bad'}}});assert(o.presentation.preset===null&&o.presentation.seat===null&&o.presentation.subject===null&&o.presentation.rendering.paint===null);});
  test('literal food only after opt-in and within presentation scope',function(){var o=first({categoryId:'food',foodGroupId:'drinks',motifId:'cream_soda',foodApplications:['literal']});C.presentation.setScope(o,'all');assert(/served separately on a tray/.test(C.generator.detailed(o)));C.presentation.setScope(o,'outfit');assert(!/served separately/.test(C.generator.detailed(o)));});
  test('food background never leaks into pose-only output',function(){var o=first({categoryId:'food',motifId:'lemon',foodGroupId:'fruits',foodApplications:['background']});C.presentation.setScope(o,'all');assert(/lemon-inspired backdrop/.test(C.generator.detailed(o)));C.presentation.setScope(o,'pose');assert(!/backdrop/.test(C.generator.detailed(o)));});
  test('concept identifier survives structured conversion without source prose dump',function(){var o=first(sample),text=C.generator.detailed(o);assert(/aurora-inspired/.test(text));assert(!/flowing light curtains|long atmospheric arcs/.test(text));});
  test('Art Nouveau concept and existing style are not repeated',function(){var o=first({categoryId:'art',motifId:'art_nouveau'}),text=C.generator.detailed(o);assert((text.match(/art[ -]nouveau/gi)||[]).length===1);});
  test('existing theme alias suppresses synonymous concept identity',function(){var o=first({categoryId:'myth',motifId:'mermaid_tale'});o.concept.primaryThemeMotif='sea_and_mermaid';assert(!C.generator.blocks(o).conceptInspiration.short.length);});
  test('same mapped colors and materials output once',function(){var o=first(sample);o.palette.primary=o.palette.secondary=o.palette.accent='emerald_green';o.materials.primary=o.materials.secondary=o.materials.trim='velvet';var text=C.generator.detailed(o);assert((text.match(/emerald green/g)||[]).length===1,text);assert((text.match(/velvet/g)||[]).length===1,text);});
  test('qipao frog fastening not duplicated as decoration',function(){var text=C.generator.detailed(first(qipao));assert((text.match(/frog closures/g)||[]).length===1,text);});
  test('crystal horns avoid crystal crystalline repetition',function(){var text=C.generator.detailed(first({categoryId:'fantasy',motifId:'crystal_dragon',baseId:'armor'}));assert(!/crystal crystalline/.test(text));});
  test('custom identifier is short and customTags remain exact',function(){var o=first({customMotif:'忘れられた約束',baseId:'dress'});o.output.customTags='(unchanged:1.2), Keep';assert(C.generator.detailed(o).endsWith(o.output.customTags));assert(/custom "忘れられた約束" concept/.test(C.generator.detailed(o)));});
  test('all concept category candidates pass existing hard-rule checks',function(){F.motifs.forEach(function(m){var cs=candidates({categoryId:m.category,motifId:m.id,foodGroupId:m.groupId});assert(cs.length===3,m.id);cs.forEach(function(c){assert(!c.warnings.some(function(w){return w.severity==='hard';}),m.id);});});});
  test('explicit tailoring placements affect their corresponding slots',function(){var o=first({categoryId:'fantasy',motifId:'moon_witch',baseId:'dress',placements:['sleeves','neckline','hem','headpiece'],strengthId:'total'});assert(o.parts.sleeves==='bell_sleeves'&&o.parts.collar==='high_standing_collar'&&o.parts.headwear==='circlet');});
  test('traditional treatment is informational, not a conflict',function(){var o=first({categoryId:'traditional',traditional:{attireId:'hanbok',treatmentId:'fantasy'}});var issues=C.advisor.check(o).filter(function(w){return w.id==='concept_cultural_note';});assert(issues.length===1&&issues[0].severity==='info');});
  test('all detail profile target IDs are real and normalized',function(){Object.keys(C.conceptFashion.detailProfiles).forEach(function(k){Object.keys(C.conceptFashion.detailProfiles[k]).forEach(function(id){var p=C.conceptFashion.detailProfiles[k][id];if(p.garment)assert(U.byId(D.garments,p.garment));if(p.style)assert(U.byId(D.styles,p.style));if(p.material)assert(U.byId(D.materials,p.material));(p.decorations||[]).forEach(function(d){assert(U.byId(D.decorations,d));});Object.keys(p.parts||{}).forEach(function(slot){assert(U.byId(U.byId(D.partSlots,slot).options,p.parts[slot]),k+'.'+id+'.'+slot);});});});});
  test('partial existing design is detected for adoption confirmation',function(){assert(!C.conceptFashion.hasDesign({}));assert(C.conceptFashion.hasDesign({concept:{primaryStyle:'gothic'}}));assert(C.conceptFashion.hasDesign({parts:{sleeves:'long_sleeves'}}));});
  test('preserve mode retains dormant styling and condition choices',function(){var o=C.schema.normalize({garment:{category:'merfolk',subtype:'sea_silk_mermaid_outfit'},styling:{items:['half_tucked']},condition:{items:[{type:'rain_soaked'}]}});var c=C.conceptFashion.buildCandidates(sample,{seed:1,currentOutfit:o,mode:'preserve'})[0].outfit;assert(JSON.stringify(c.styling)===JSON.stringify(o.styling));assert(JSON.stringify(c.condition)===JSON.stringify(o.condition));assert(!/half-tucked/.test(C.generator.detailed(c)));});
  test('audit regression: mapped long sleeves swap incompatible slip-dress base',function(){var s={categoryId:'concept',motifId:'jealousy',baseId:'gown',strengthId:'bold',exposure:2,directions:['comic'],placements:['sleeves','neckline','hem','headpiece']},cs=candidates(s);assert(cs.length===3);cs.forEach(function(c){assert(!c.warnings.some(function(w){return w.severity==='hard';}));});assert(JSON.stringify(candidates(s))===JSON.stringify(candidates(s)));});
  test('audit regression: constrained base uses advisor resolution without losing garment',function(){var s={categoryId:'fantasy',motifId:'moon_witch',baseId:'bodysuit',exposure:0,placements:['sleeves','neckline'],strengthId:'total'},cs=candidates(s);assert(cs.length===3);cs.forEach(function(c){assert(c.outfit.garment.subtype);assert(!c.warnings.some(function(w){return w.severity==='hard';}));});});
  test('traditional category clears stale idol silhouette settings',function(){var o=first({categoryId:'traditional',baseId:'idol',idolStyleId:'unisex',traditional:{attireId:'hanbok',treatmentId:'traditional'}});assert(o.garment.subtype==='hanbok');assert(o.concept.inspiration.idolStyleId===null);});
  test('preserved hanbok does not acquire qipao-specific structure',function(){var o=C.schema.normalize({garment:{category:'top_bottom',subtype:'hanbok'}}),cs=C.conceptFashion.buildCandidates(qipao,{seed:5,currentOutfit:o,mode:'preserve'});assert(cs.length===3);cs.forEach(function(c){assert(c.outfit.garment.subtype==='hanbok');assert(!/frog closure|mandarin collar/.test(C.generator.detailed(c.outfit)));assert(c.reasons.some(function(r){return r.source==='compatibility';}));});});
})(typeof window!=='undefined'?window:global);
