/* Phase 5E: actual structured outcomes, constraints and compatibility. */
(function(g){
  'use strict';var C=g.CPW,D=C.data,F=D.conceptFashion,E=C.conceptFashion,U=C.util;
  function assert(v,m){if(!v)throw Error(m||'Phase 5E assertion');}
  function test(n,fn){C.tests.push({name:'5E: '+n,fn:fn});}
  function profile(p){
    ['colors','materials','decorations','patterns','styles','garments'].forEach(function(k){(p[k]||[]).forEach(function(id){assert(U.byId(D[k],id),k+':'+id);});});
    Object.keys(p.parts||{}).forEach(function(k){var slot=U.byId(D.partSlots,k);assert(slot,k);p.parts[k].forEach(function(id){assert(U.byId(slot.options,id),k+':'+id);});});
    Object.keys(p.silhouette||{}).forEach(function(k){p.silhouette[k].forEach(function(id){assert(U.byId(D.silhouette[k],id),k+':'+id);});});
    (p.conditionTypes||[]).forEach(function(id){assert(U.byId(D.conditions,id),id);assert(id.indexOf('blood')<0,'automatic blood');});
    (p.styling||[]).forEach(function(id){assert(U.byId(D.styling,id),id);});
  }
  function candidates(s,opts){var raw=JSON.stringify(s),state=JSON.stringify(C.state.outfit),cs=E.buildCandidates(s,Object.assign({seed:31},opts||{}));assert(cs.length===3,'expected 3, got '+cs.length);assert(raw===JSON.stringify(s)&&state===JSON.stringify(C.state.outfit),'preview mutation');return cs;}
  F.motifs.forEach(function(m){test('motif '+m.id+' has usable explicit visual translation',function(){profile(m.recommended);assert(m.summaryJa&&m.fallback.shape&&m.fallback.detail);var cs=candidates({categoryId:m.category,motifId:m.id,foodGroupId:m.groupId});cs.forEach(function(c){assert(c.strategy&&c.motifContributions.some(function(v){return v.source==='primary'&&v.paths.length;}),'missing contribution');assert(c.outfit.materials.primary||c.outfit.palette.primary||Object.keys(c.outfit.parts).length);assert(!c.outfit.condition.items.some(function(x){return /blood/.test(x.type);}));assert(!/undefined|NaN|inspired-inspired/.test(C.generator.detailed(c.outfit)));});});});
  ['worldviews','eras','roles','occasions'].forEach(function(k){D[k].forEach(function(v){test(k+' '+v.id+' affects structured context',function(){profile(v.recommended);var key={worldviews:'worldview',eras:'era',roles:'role',occasions:'occasion'}[k],ctx={};ctx[key+'Id']=v.id;var cs=candidates({context:ctx,baseId:'suit'});cs.forEach(function(c){assert(c.outfit.concept[key]===v.id);assert(c.outfit.garment.category==='uniform','explicit base');assert(c.reasons.some(function(r){return r.source==='context';}));});});});});
  F.storyStates.forEach(function(v){test('story '+v.id+' uses shared condition and styling',function(){profile(v.recommended);var cs=candidates({context:{storyStateIds:[v.id]},baseId:'coat'});cs.forEach(function(c){assert(c.outfit.condition.items.length<=2&&c.outfit.styling.items.length<=2);assert(!c.outfit.condition.items.some(function(x){return /blood/.test(x.type);}));assert(C.styling.active(c.outfit).length===c.outfit.styling.items.length);assert(c.outfit.condition.items.length===v.recommended.conditionTypes.length);});});});
  F.designLanguages.forEach(function(v){test('language '+v.id+' maps silhouette and construction',function(){profile(v.recommended);candidates({designLanguages:[v.id],baseId:'dress'}).forEach(function(c){assert(c.outfit.silhouette.fit===v.recommended.silhouette.fit[0]);assert(c.outfit.parts.construction_detail===v.recommended.parts.construction_detail[0]);});});});
  F.exclusions.forEach(function(v){test('exclusion '+v.id+' is a hard candidate constraint',function(){var cs=E.buildCandidates({categoryId:'fantasy',motifId:'celestial',exclusions:[v.id],placements:['palette','materials','special','ornament']},{seed:11});assert(cs.length>0);cs.forEach(function(c){assert(!E.constraintViolations(c.outfit,[v.id]).length);assert(c.constraintsApplied.indexOf(v.id)>=0);assert(!/no frills|no lace/.test(C.generator.detailed(c.outfit)));});});});
  F.blendModes.forEach(function(v){test('blend '+v.id+' routes secondary into owned slots',function(){candidates({categoryId:'nature',motifId:'deep_sea',secondary:{categoryId:'art',motifId:'gothic_cathedral'},blendMode:v.id}).forEach(function(c){assert(c.outfit.palette.primary);assert(c.motifContributions.some(function(x){return x.source==='secondary'&&x.paths.length;}),'secondary lost');if(v.id==='secondary_accent')assert(c.motifContributions[1].paths.every(function(p){return p==='decorations.items';}));});});});
  F.randomProfiles.forEach(function(p){test('random '+p.id+' reproduces selection and avoids sensitive random defaults',function(){var a=E.randomSelection(p.id,71),b=E.randomSelection(p.id,71);assert(JSON.stringify(a)===JSON.stringify(b));assert(JSON.stringify(a)!==JSON.stringify(E.randomSelection(p.id,72)));assert(a.categoryId!=='traditional'&&a.exposure===null);assert(a.foodApplications.indexOf('literal')<0);assert(a.secondary.motifId!==a.motifId);});});
  test('selection limits and unknown expansion IDs',function(){var s=E.normalizeSelection({secondary:{categoryId:'wrong',motifId:'rain'},blendMode:'bad',context:{roleId:'bad',storyStateIds:F.storyStates.map(function(x){return x.id;})},designLanguages:F.designLanguages.map(function(x){return x.id;}),exclusions:F.exclusions.map(function(x){return x.id;}),interpretationMode:'bad'});assert(s.secondary.motifId===null&&s.context.roleId===null);assert(s.context.storyStateIds.length===2&&s.designLanguages.length===2&&s.exclusions.length===4&&s.interpretationMode==='auto');});
  test('same motif is not applied as a secondary a second time',function(){candidates({categoryId:'nature',motifId:'deep_sea',secondary:{categoryId:'nature',motifId:'deep_sea'}}).forEach(function(c){assert(c.motifContributions.length===1);});});
  test('strict incompatible explicit base returns no invalid candidate',function(){assert(E.buildCandidates({baseId:'dress',exclusions:['no_dress']},{seed:1}).length===0);});
  test('preserve conflict requires a decision without mutating source',function(){var original=C.schema.normalize({garment:{category:'dress',subtype:'cocktail_dress'},decorations:{items:[{type:'frills'}]}}),raw=JSON.stringify(original);var c=candidates({exclusions:['no_frills']},{mode:'preserve',currentOutfit:original})[0];assert(c.conflicts.length&&c.outfit.decorations.items[0].type==='frills');assert(JSON.stringify(original)===raw);assert(E.resolvePreserveConflict(c,'keep').decorations.items[0].type==='frills');assert(E.resolvePreserveConflict(c,'exclude').decorations.items.length===0);});
  test('custom subject is never used to guess palette or material',function(){candidates({customMotif:'忘れられた約束'}).forEach(function(c){assert(c.outfit.palette.primary===null&&c.outfit.materials.primary===null);assert(c.outfit.output.customTags==='');});});
  test('actual main 0.5 fixtures migrate with byte-identical prompt text',function(){assert(C.fixtures05.length===144);C.fixtures05.forEach(function(f){var r=C.schema.migrate(f.outfit),s=r.outfit.concept.inspiration;assert(r.ok&&r.outfit.version==='0.6');assert(!s.secondary.motifId&&!s.context.roleId&&!s.exclusions.length);assert(s.motifId===f.outfit.concept.inspiration.motifId);assert(C.generator.short(r.outfit)===f.short,'0.5 short '+s.motifId);assert(C.generator.detailed(r.outfit)===f.detailed,'0.5 detailed '+s.motifId);});});
  function withStore(fn){var read=C.store._read,write=C.store._write,m={};C.store._read=function(k,d){return m[k]?U.clone(m[k]):d;};C.store._write=function(k,v){m[k]=U.clone(v);return true;};try{fn();}finally{C.store._read=read;C.store._write=write;}}
  ['normalize','draft','library','duplicate','json','allJson'].forEach(function(method){test('schema 0.6 '+method+' retains the complete concept and user tags',function(){withStore(function(){var s=E.randomSelection('dark',13);s.exclusions=['no_wings','no_halo'];s.secondary.customMotif='忘れられた約束';s.designLanguages=['linear','layered'];s.interpretationMode='symbolic';var o=candidates(s)[0].outfit;o.output.customTags='  Exact,(User_Tag:1.4), 日本語  ';var copy;
    if(method==='normalize')copy=C.schema.normalize(JSON.parse(JSON.stringify(o)));
    if(method==='draft'){C.store.saveDraft(o);copy=C.store.loadDraft();}
    if(method==='library'){C.store.saveOutfit(o);copy=C.store.getOutfit(o.id);}
    if(method==='duplicate'){C.store.saveOutfit(o);copy=C.store.duplicateOutfit(o.id);assert(copy.id!==o.id);}
    if(method==='json'){assert(C.store.importJSON(C.store.exportOutfit(o)).ok);copy=C.store.listOutfits()[0];}
    if(method==='allJson'){C.store.saveOutfit(o);assert(C.store.importJSON(C.store.exportAll()).ok);copy=C.store.listOutfits()[0];}
    ['concept','garment','specialParts','styling','condition','presentation','output'].forEach(function(k){assert(JSON.stringify(o[k])===JSON.stringify(copy[k]),method+' '+k);});assert(copy.version==='0.6');
  });});});
  test('A deep sea and cathedral split visual responsibilities',function(){var cs=candidates({categoryId:'nature',motifId:'deep_sea',secondary:{categoryId:'art',motifId:'gothic_cathedral'},blendMode:'split_roles',directions:['mystical'],designLanguages:['vertical','organic']});cs.forEach(function(c){assert(['deep_navy','teal','pale_cyan'].indexOf(c.outfit.palette.primary)>=0);assert(c.outfit.silhouette.fit==='slim_fit');assert(c.outfit.parts.construction_detail==='overlapping_panels');assert(c.motifContributions.some(function(x){return x.source==='secondary'&&x.paths.length;}));assert(!/deep-sea-inspired.*cathedral-inspired/.test(C.generator.detailed(c.outfit)));});});
  test('B poison flower symbolism obeys no floral decoration',function(){candidates({categoryId:'fantasy',motifId:'poison',secondary:{categoryId:'living',motifId:'flower'},interpretationMode:'symbolic',exclusions:['no_flower_decoration']}).forEach(function(c){assert(!E.constraintViolations(c.outfit,['no_flower_decoration']).length);assert(['lime_green','eggplant','ink_black'].indexOf(c.outfit.palette.primary)>=0);assert(c.outfit.parts.construction_detail);});});
  test('C butterfly machine strategies differ beyond color',function(){var cs=candidates({categoryId:'living',motifId:'butterfly',secondary:{categoryId:'material',motifId:'machine'},blendMode:'balanced'});assert(E.diversity(cs).count>=2);assert(cs.map(function(c){return c.strategy;}).join(',')==='readable,wearable,experimental');assert(cs[1].outfit.parts.construction_detail==='shaped_seams');assert(cs[2].outfit.parts.construction_detail==='modular_panels');});
  test('D former royalty retains quality and gains repair and travel practicality',function(){candidates({context:{roleId:'royal_prince',storyStateIds:['fallen_status'],worldviewId:'western_fantasy',occasionId:'travel'}}).forEach(function(c){assert(['silk','brocade'].indexOf(c.outfit.materials.primary)>=0);assert(c.outfit.condition.items.some(function(x){return x.type==='repaired';}));assert(!/blood/.test(C.generator.detailed(c.outfit)));assert(c.outfit.concept.occasion==='travel');});});
  test('E scholarly stars reflect current Victorian research context',function(){var cs=candidates({categoryId:'nature',motifId:'star',context:{roleId:'scholar',occasionId:'research',eraId:'victorian_era'}});cs.forEach(function(c){assert(c.outfit.concept.primaryStyle==='dark_academia');assert(c.outfit.concept.era==='victorian_era');});assert(E.diversity(cs).count>=2);});
  test('F celestial design can be sacred without special parts',function(){candidates({categoryId:'fantasy',motifId:'celestial',placements:['palette','materials','special','ornament'],exclusions:['no_wings','no_halo','no_special_parts']}).forEach(function(c){assert(!C.schema.activeSpecialParts(c.outfit).length);assert(c.outfit.palette.primary);});});
  test('G moon knight preserves merfolk hard structure',function(){var o=C.schema.normalize({garment:{category:'merfolk',subtype:'sea_silk_mermaid_outfit'}});candidates({categoryId:'nature',motifId:'full_moon',secondary:{categoryId:'myth',motifId:'knight_tale'}},{mode:'preserve',currentOutfit:o}).forEach(function(c){assert(c.outfit.garment.category==='merfolk');var text=C.generator.detailed(c.outfit).replace(/no human legs|no feet|replacing separate human legs and feet/g,'');assert(!/\b(trousers|shoes|knee|legs|boots|pants)\b/.test(text));});});
  test('H after battle changes clothing only, no automatic blood',function(){candidates({context:{roleId:'knight',storyStateIds:['after_battle']}}).forEach(function(c){assert(c.outfit.condition.items.some(function(x){return x.type==='battle_worn';}));assert(!/blood|wound|injur/.test(C.generator.detailed(c.outfit)));});});
  test('I preserve exclusion warnings are shared with advisor',function(){var o=C.schema.normalize({decorations:{items:[{type:'frills'}]}});var cs=candidates({exclusions:['no_frills']},{mode:'preserve',currentOutfit:o});cs.forEach(function(c){assert(c.warnings.some(function(w){return w.id==='concept_exclusions';}));assert(c.outfit.decorations.items[0].type==='frills');});});
  test('J dark random concept is reproducible without traditional or extreme defaults',function(){var a=E.randomSelection('dark',999);assert(a.directions.indexOf('dark')>=0&&a.exposure===null&&!a.traditional.attireId);assert(JSON.stringify(a)===JSON.stringify(E.randomSelection('dark',999)));});
  test('K 100 different selections have structural diversity',function(){for(var i=0;i<100;i++){var cs=candidates(E.randomSelection(F.randomProfiles[i%F.randomProfiles.length].id,i+100));var d=E.diversity(cs);assert(d.count>=2,'seed '+i+': '+JSON.stringify(d));for(var j=0;j<3;j++)for(var k=j+1;k<3;k++)assert(E.diversity([cs[j],cs[k]]).structural,'color-only pair seed '+i);}});
  test('L old inspiration becomes empty expansion fields',function(){var f=C.fixtures05[60],o=C.schema.migrate(f.outfit).outfit,s=o.concept.inspiration;assert(s.motifId===f.outfit.concept.inspiration.motifId);assert(s.blendMode==='primary_dominant'&&s.interpretationMode==='auto');assert(!s.secondary.motifId&&!s.context.storyStateIds.length&&!s.designLanguages.length&&!s.exclusions.length);});
  test('O custom primary plus rain never guesses from unknown text',function(){var a=candidates({customMotif:'忘れられた約束',secondary:{categoryId:'nature',motifId:'rain'},blendMode:'balanced'})[0].outfit,b=candidates({customMotif:'未知の言葉',secondary:{categoryId:'nature',motifId:'rain'},blendMode:'balanced'})[0].outfit;assert(a.palette.primary===null&&a.materials.primary===null);assert(a.materials.secondary===b.materials.secondary);assert(a.palette.secondary===b.palette.secondary);});
  test('P traditional core survives secondary and avant strategy',function(){candidates({categoryId:'traditional',traditional:{attireId:'qipao',treatmentId:'traditional'},secondary:{categoryId:'material',motifId:'machine'},blendMode:'balanced'}).forEach(function(c){assert(c.outfit.garment.subtype==='qipao');assert(c.outfit.parts.collar==='mandarin_collar'&&c.outfit.parts.closure==='frog_closures');assert(!c.outfit.parts.cutout);});});
  test('Q cream soda and night sky stay abstract unless literal food explicitly requested',function(){candidates({categoryId:'food',foodGroupId:'drinks',motifId:'cream_soda',secondary:{categoryId:'nature',motifId:'night_sky'},blendMode:'balanced'}).forEach(function(c){assert(c.outfit.palette.primary&&c.outfit.materials.primary);assert(!/holding|on a tray|food attached/.test(C.generator.detailed(c.outfit)));});});
  test('R interpretation changes structure instead of just fallback text',function(){var structures=['literal','symbolic','abstract','fashion','avant_garde'].map(function(mode){var c=candidates({categoryId:'living',motifId:'rose',interpretationMode:mode})[0];return JSON.stringify([c.outfit.silhouette,c.outfit.parts,c.outfit.decorations]);});assert(new Set(structures).size===5);});
  test('conflicting story and creative era-role mixes are warnings only',function(){var c=candidates({categoryId:'traditional',traditional:{attireId:'kimono'},context:{eraId:'far_future',roleId:'knight',occasionId:'research',storyStateIds:['prime','fallen_status']}})[0];['concept_story','concept_era','concept_role'].forEach(function(id){assert(c.warnings.some(function(w){return w.id===id&&w.severity==='warning';}),id);});});
  test('current concept values override recorded inspiration in generated output',function(){var c=candidates({context:{roleId:'knight',worldviewId:'western_fantasy'}})[0];c.outfit.concept.role='scholar';c.outfit.concept.worldview='modern';assert(!/knight/.test(C.generator.short(c.outfit)));assert(c.outfit.concept.inspiration.context.roleId==='knight');});
  test('explicit abstract ornament mappings refer to real decorations',function(){Object.keys(F.decorationInterpretations).forEach(function(id){assert(U.byId(D.decorations,id));Object.values(F.decorationInterpretations[id]).forEach(function(ids){ids.forEach(function(id){assert(U.byId(D.decorations,id),id);});});});});
  test('multi-value part exclusions inspect actual IDs and preserve compatible layers',function(){var o=C.schema.normalize({parts:{cutout:[{id:'open_back',layer:'main'}],asymmetry_detail:'single_shoulder_guard'}});assert(E.constraintViolations(o,['no_cutouts','no_armor']).length>=2);var r=E.enforceExclusions(o,E.normalizeSelection({exclusions:['no_cutouts','no_armor']}));assert(r.unresolved.length===0);});
  test('ornament constraints include quantity and physical size',function(){var o=C.schema.normalize({decorations:{items:[{type:'beadwork',quantity:'many',size:'large'}]}});var r=E.enforceExclusions(o,E.normalizeSelection({exclusions:['minimal_ornament','no_large_ornament']}));assert(!r.unresolved.length);assert(r.outfit.decorations.items[0].quantity==='single'&&r.outfit.decorations.items[0].size==='medium');});
  test('rose and machinery have different abstract ornament translations',function(){var a=candidates({categoryId:'living',motifId:'rose',interpretationMode:'abstract'})[0].outfit,b=candidates({categoryId:'material',motifId:'machine',interpretationMode:'abstract'})[0].outfit;assert(a.decorations.items[0].type==='pleated_trim');assert(b.decorations.items[0].type==='grommets');});
  test('exclusion membership only references existing target IDs',function(){var parts=D.partSlots.reduce(function(a,s){return a.concat(s.options||[]);},[]),special=D.specialParts.slots.reduce(function(a,s){return a.concat(C.schema.axisOf(s,'type').options);},[]);Object.keys(F.exclusionRules).forEach(function(id){assert(U.byId(F.exclusions,id),id);var r=F.exclusionRules[id];Object.keys(r).forEach(function(k){var list={parts:parts,silhouette:Object.keys(D.silhouette).reduce(function(a,k){return a.concat(D.silhouette[k]);},[]),specialTypes:special,specialSlots:D.specialParts.slots}[k]||D[k];if(!Array.isArray(list))return;(r[k]||[]).forEach(function(target){assert(U.byId(list,target),id+' '+k+' '+target);});});});});
  ['worldviews','eras','roles','occasions'].forEach(function(k){test(k+' IDs remain unique snake_case with labels',function(){var seen={};D[k].forEach(function(x){assert(/^[a-z][a-z0-9_]*$/.test(x.id)&&!seen[x.id],x.id);seen[x.id]=true;assert(x.labelJa&&x.shortPrompt);});});});
})(window);
