/* Browser acceptance tests. Playwright is a development-only dependency. */
const fs=require('fs'),path=require('path'),http=require('http'),pw=require('playwright');
const root=path.resolve(__dirname,'..'),engine=process.env.CPW_ENGINE||'chromium',out=path.resolve(process.argv[2]||path.join(root,'verification/phase5f-ui-'+engine+'.json'));
const assert=(v,m)=>{if(!v)throw Error(m);},report={engine,cases:[],errors:[],nativeIPhone:false};
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost'),f=path.resolve(root,'.'+(u.pathname==='/'?'/index.html':u.pathname));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(f));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await pw[engine].launch({headless:true,...(engine==='chromium'?{channel:'msedge'}:{})});report.browser=browser.version();const home='http://127.0.0.1:'+server.address().port+'/';
try{for(const width of (process.env.CPW_SMOKE?[390]:[375,390,430])){
  const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.stack));page.on('dialog',async d=>{report.errors.push('Unexpected native dialog');await d.dismiss();});
  const check=async name=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+name);report.cases.push({width,name});};
  const level=async(surface,value)=>{await page.locator('[data-ui-surface="'+surface+'"] [data-ui-level="'+value+'"]').click();};
  await page.goto(home);await page.getByRole('link',{name:'細かく選んで作る',exact:true}).click();await page.waitForURL('**/#/entry');await page.getByRole('heading',{name:'何から始める？'}).waitFor();assert(await page.locator('a[href*="concept_fashion"]').count()===0,'entry duplication');assert(await page.locator('a[href^="#/setup/"]').count()===5,'five entry routes');await check('entry');
  await page.evaluate(()=>{CPW.state.reset();location.hash='#/workshop';});await page.locator('#panel-concept').waitFor();
  const clean=await page.evaluate(()=>({json:JSON.stringify(CPW.state.outfit),dirty:CPW.state.dirty,export:JSON.stringify(JSON.parse(CPW.store.exportOutfit(CPW.state.outfit)).outfit)}));
  assert(await page.locator('.acc-head').count()===4,'simple four sections');assert(await page.locator('[data-fkey="concept.era:modern_era"]').count()===0,'hidden era');await check('simple workshop');
  await level('workshop','advanced');assert(await page.locator('.acc-head').count()===7,'advanced seven sections');await check('advanced workshop');await level('workshop','simple');
  assert(await page.evaluate(before=>before.json===JSON.stringify(CPW.state.outfit)&&before.dirty===CPW.state.dirty&&before.export===JSON.stringify(JSON.parse(CPW.store.exportOutfit(CPW.state.outfit)).outfit),clean),'mode modifies data');
  await page.evaluate(()=>{const C=CPW;C.state.load(C.schema.normalize({garment:{category:'merfolk',subtype:'sea_silk_mermaid_outfit'},parts:{mermaid_tail_form:'flowing_mermaid_tail'},materials:{secondary:'organza'},palette:{primary:'jet_black',secondary:'charcoal_gray',scheme:'monochrome'},condition:{items:[{type:'repaired'}]},concept:{inspiration:{categoryId:'material',motifId:'stained_glass',secondary:{categoryId:'object',motifId:'hourglass'},context:{roleId:'knight'},directions:['mystical','elegant'],designLanguages:['linear'],exclusions:['no_wings']}}}));C.render();window.preserved=JSON.stringify(C.state.outfit);window.promptBefore=C.generator.detailed(C.state.outfit);});
  assert((await page.locator('[data-hidden-summary="workshop"]').innerText()).includes('状態・加工'),'missing hidden condition');await page.locator('[aria-controls="panel-structure"]').click();assert(await page.locator('[data-fkey^="part:mermaid_tail_form:"]').count()>0,'required tail hidden');await check('simple merfolk');
  await level('workshop','advanced');await level('workshop','simple');assert(await page.evaluate(()=>preserved===JSON.stringify(CPW.state.outfit)&&promptBefore===CPW.generator.detailed(CPW.state.outfit)),'hidden values lost');
  await page.evaluate(()=>{location.hash='#/concept_fashion/edit';});await page.locator('#cf-categoryId').waitFor();assert(await page.locator('.cf-steps button').count()===3,'simple three steps');assert((await page.locator('[data-hidden-summary="concept"]').innerText()).includes('砂時計'),'secondary summary absent');
  await page.locator('#cf-next').click();assert(await page.locator('#cf-direction').inputValue()==='mystical','first direction');await level('concept','advanced');assert(await page.locator('#cf-baseId').isVisible(),'semantic step mapping');await level('concept','simple');await page.locator('#cf-next').click();await level('concept','advanced');assert(await page.locator('#cf-exposure').isVisible(),'finish mapping');await level('concept','simple');
  await page.locator('#cf-generate').click();assert(await page.locator('[data-cf-adopt]').count()===3,'hidden draft preview');assert(await page.evaluate(()=>preserved===JSON.stringify(CPW.state.outfit)),'preview mutation');await check('hidden concept preview');
  await page.getByRole('button',{name:'1 題材',exact:true}).click();await page.locator('#cf-search').fill('xyz-no-such-motif');assert((await page.locator('#cf-search-results').innerText()).includes('見つかりません'),'zero result');await page.locator('#cf-search-all').check();await page.locator('#cf-search').fill('hourglass');await page.locator('[data-cf-search-result="hourglass"]').click();assert(await page.locator('#cf-categoryId').inputValue()==='object'&&await page.locator('#cf-motifId').inputValue()==='hourglass','search selection');await check('search object');
  await page.locator('#cf-categoryId').selectOption('food');assert(await page.locator('#cf-categoryId').inputValue()==='food','category lost');assert(!await page.locator('#cf-categoryId').evaluate(e=>e===document.activeElement),'select refocused');await page.locator('#cf-foodGroupId').selectOption('drinks');await page.locator('#cf-motifId').selectOption('cream_soda');await check('two-stage food');
  await level('concept','advanced');await page.locator('#cf-categoryId').selectOption('traditional');await page.locator('#cf-traditional-regionId').selectOption('east_asia');await page.locator('#cf-traditional-attireId').selectOption('qipao');assert(await page.locator('#cf-traditional-qipaoNecklineId').isVisible(),'qipao details');await check('advanced qipao');
  for(const surfaceLevel of ['simple','advanced'])for(const existing of [false,true])for(const mode of (existing?['new','preserve']:['new']))for(const motif of (process.env.CPW_SMOKE?['mille_feuille']:['mille_feuille','hourglass','stained_glass']))for(const index of [0,1,2]){
    await page.goto(home);await page.evaluate(({surfaceLevel,existing,index})=>{const C=CPW;C.uiPrefs.set('concept',surfaceLevel);C.uiPrefs.set('workshop',index%2?'advanced':'simple');C.state.load(existing?C.schema.normalize({garment:{category:'dress',subtype:'cocktail_dress'},palette:{primary:'jet_black'},output:{customTags:'KEEP_Exact'}}):C.schema.createOutfit());window.before=JSON.stringify(C.state.outfit);const build=C.conceptFashion.buildCandidates;C.conceptFashion.buildCandidates=function(s,opts){window.draftBefore=JSON.stringify(s);const cs=build(s,{...opts,seed:index+71});window.previews=JSON.parse(JSON.stringify(cs));return cs;};location.hash='#/concept_fashion';},{surfaceLevel,existing,index});
    const category={mille_feuille:'food',hourglass:'object',stained_glass:'material'}[motif];await page.locator('#cf-categoryId').selectOption(category);if(category==='food')await page.locator('#cf-foodGroupId').selectOption('sweets');await page.locator('#cf-motifId').selectOption(motif);await page.getByRole('button',{name:surfaceLevel==='simple'?'2 雰囲気・衣装':'4 衣装',exact:true}).click();if(existing)await page.locator('[data-cf-mode="'+mode+'"]').click();await page.getByRole('button',{name:surfaceLevel==='simple'?'3 仕上げ':'5 反映',exact:true}).click();await page.locator('#cf-generate').click();
    // Switching levels with an existing preview must retain candidate objects and draft.
    await level('concept',surfaceLevel==='simple'?'advanced':'simple');await level('concept',surfaceLevel);assert(await page.locator('[data-cf-adopt]').count()===3,'preview discarded on switch');assert(await page.evaluate(()=>before===JSON.stringify(CPW.state.outfit)),'preview touched state');
    await page.locator('[data-cf-adopt="'+index+'"]').click();if(existing)await page.locator('[data-cf-confirm="apply"]').click();await page.locator('#panel-concept').waitFor({state:'visible'});
    const snapshot=await page.evaluate(index=>{const C=CPW;function content(o){const a=JSON.parse(JSON.stringify(o));delete a.id;delete a.createdAt;delete a.updatedAt;return JSON.stringify(a);}if(location.hash!=='#/workshop'||content(C.state.outfit)!==content(C.schema.normalize(previews[index].outfit)))throw Error('wrong adopted candidate');if(C.uiPrefs.get('workshop')!==(index%2?'advanced':'simple'))throw Error('copied concept level');C._autosave.flush();return JSON.stringify(C.state.outfit);},index);
    await page.reload();await page.locator('#panel-concept').waitFor();assert(await page.evaluate(snapshot=>snapshot===JSON.stringify(CPW.state.outfit),snapshot),'reload lost data');await check('adopt '+surfaceLevel+' '+existing+' '+mode+' '+motif+' '+index);
  }
  await page.evaluate(()=>{CPW.uiPrefs.set('concept','simple');location.hash='#/concept_fashion';});await page.locator('#cf-categoryId').waitFor();await page.locator('#cf-categoryId').selectOption('object');await page.screenshot({path:path.join(path.dirname(out),'phase5f-'+engine+'-'+width+'.png'),fullPage:true});
  const small=await page.locator('.ui-level-switch button,.cf-steps button,#cf-random,[data-cf-featured]').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().height<44).map(e=>e.textContent));assert(!small.length,'small targets '+small);await check('44px targets');
  await context.close();console.log(engine+' '+width+'px: '+report.cases.length+' checks passed');
}
assert(!report.errors.length,report.errors.join('\n'));fs.writeFileSync(out,JSON.stringify(report,null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
