/* Optional development QA; Playwright is not an application dependency. */
const fs=require('fs'),path=require('path'),http=require('http'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||path.join(root,'verification/phase5d-ui.json'));
const screenshotDir=path.resolve(process.env.CPW_SCREENSHOT_DIR||path.join(path.dirname(out),'screenshots'));fs.mkdirSync(screenshotDir,{recursive:true});
const assert=(v,m)=>{if(!v)throw Error(m)};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.CPW_BROWSER_CHANNEL||'msedge'}),report={browser:browser.version(),viewports:[],errors:[]};
try{for(const width of [375,390,430]){const page=await browser.newPage({viewport:{width,height:844}});page.on('pageerror',e=>report.errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/');const before=await page.evaluate(()=>JSON.stringify(CPW.state.outfit));
await page.getByRole('link',{name:'コンセプトから作る',exact:true}).click();await page.locator('#cf-categoryId').selectOption('nature');await page.locator('#cf-motifId').selectOption('aurora');await page.locator('#cf-next').click();await page.locator('#cf-next').click();await page.locator('[data-cf="directions:fantastical"]').click();await page.locator('#cf-next').click();await page.locator('#cf-baseId').selectOption('gown');await page.locator('#cf-next').click();await page.locator('#cf-strengthId').selectOption('bold');await page.locator('#cf-generate').click();assert(await page.locator('.cf-candidate').count()===3,'three previews');assert(before===await page.evaluate(()=>JSON.stringify(CPW.state.outfit)),'preview mutated state');
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'horizontal overflow');const small=await page.locator('.concept-wizard button, .concept-wizard select, .concept-wizard summary').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&(r.width<44||r.height<44)}).map(n=>n.textContent));assert(!small.length,'small targets '+small);
await page.locator('[data-cf-adopt="0"]').click();await page.locator('#panel-concept').waitFor({state:'visible'});assert(await page.evaluate(()=>CPW.state.outfit.entryMode==='concept_fashion'),'adoption');await page.evaluate(()=>CPW._autosave.flush());await page.reload();assert(await page.evaluate(()=>CPW.state.outfit.concept.inspiration.motifId==='aurora'),'reload');
await page.getByRole('link',{name:/コンセプトを編集/}).click();assert(await page.locator('#cf-motifId').inputValue()==='aurora','reedit');
// Food uses a category -> group -> motif flow, and cancelled adoption leaves state intact.
const adopted=await page.evaluate(()=>JSON.stringify(CPW.state.outfit));
await page.locator('#cf-categoryId').selectOption('food');assert(await page.locator('#cf-motifId').count()===0,'food group required');
await page.locator('#cf-foodGroupId').selectOption('drinks');await page.locator('#cf-motifId').selectOption('cream_soda');
await page.getByRole('button',{name:'5 反映',exact:true}).click();await page.locator('#cf-generate').click();assert(adopted===await page.evaluate(()=>JSON.stringify(CPW.state.outfit)),'food preview mutated state');
page.once('dialog',d=>d.dismiss());await page.locator('[data-cf-adopt="0"]').click();assert(adopted===await page.evaluate(()=>JSON.stringify(CPW.state.outfit)),'cancel adoption changed state');
await page.getByRole('button',{name:'4 衣装',exact:true}).click();await page.locator('[data-cf-mode="preserve"]').click();await page.getByRole('button',{name:'5 反映',exact:true}).click();await page.locator('#cf-generate').click();page.once('dialog',d=>d.accept());await page.locator('[data-cf-adopt="0"]').click();await page.locator('#panel-concept').waitFor({state:'visible'});
assert(await page.evaluate(expected=>CPW.state.outfit.garment.subtype===JSON.parse(expected).garment.subtype,adopted),'preserve garment');
// Traditional qipao configuration and actual new-design adoption.
await page.getByRole('link',{name:/コンセプトを編集/}).click();await page.locator('#cf-categoryId').selectOption('traditional');await page.locator('#cf-traditional-regionId').selectOption('east_asia');await page.locator('#cf-traditional-attireId').selectOption('qipao');await page.locator('#cf-traditional-treatmentId').selectOption('traditional');await page.locator('#cf-traditional-qipaoNecklineId').selectOption('classic');await page.locator('#cf-traditional-qipaoLengthId').selectOption('long');await page.locator('#cf-traditional-qipaoSlitId').selectOption('none');await page.getByRole('button',{name:'5 反映',exact:true}).click();await page.locator('#cf-generate').click();page.once('dialog',d=>d.accept());await page.locator('[data-cf-adopt="0"]').click();await page.locator('#panel-concept').waitFor({state:'visible'});assert(await page.evaluate(()=>CPW.state.outfit.garment.subtype==='qipao'&&!/slit/.test(CPW.generator.detailed(CPW.state.outfit))),'qipao no slit');
const bars=await page.evaluate(()=>{const a=document.querySelector('.topnav').getBoundingClientRect(),b=document.querySelector('.bottombar').getBoundingClientRect();return a.bottom<=b.top;});assert(bars,'sticky and bottom bars overlap');
// Mermaid alternative, then independent presentation controls.
await page.getByRole('link',{name:/コンセプトを編集/}).click();await page.locator('#cf-categoryId').selectOption('myth');await page.locator('#cf-motifId').selectOption('mermaid_tale');await page.getByRole('button',{name:'5 反映',exact:true}).click();await page.locator('#cf-generate').click();
await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(screenshotDir,'phase5d-candidates-'+width+'.png'),fullPage:true});page.once('dialog',d=>d.accept());await page.locator('[data-cf-adopt="0"]').click();await page.locator('#panel-concept').waitFor({state:'visible'});assert(await page.evaluate(()=>CPW.state.outfit.garment.category==='merfolk'),'merfolk adoption');
await page.getByRole('link',{name:'プロンプトを見る',exact:true}).click();await page.locator('.presentation-panel summary').click();await page.locator('#pr-presentation-preset').selectOption('seated');await page.locator('#pr-presentation-seat').selectOption('armchair');await page.locator('#pr-presentation-background').selectOption('theme');await page.locator('#pr-presentation-rendering-paint').selectOption('watercolor');await page.locator('#rendering-enabled').click();
for(const scope of ['outfit','pose','all']){await page.locator('#output-scope').selectOption(scope);const blocks=await page.evaluate(()=>CPW.generator.blocks(CPW.state.outfit));assert((blocks.presentation.short.length>0)===(scope!=='outfit'),'UI presentation scope');assert((blocks.background.short.length>0)===(scope==='all'),'UI background scope');assert((blocks.rendering.short.length>0)===(scope==='all'),'UI rendering scope');}
assert(await page.locator('#pr-presentation-subject').inputValue()==='','default subject');await page.locator('#pr-presentation-preset').selectOption('standing');assert(await page.locator('#pr-presentation-seat').count()===0,'standing seat hidden');await page.locator('#pr-presentation-preset').selectOption('seated');
await page.locator('#custom-tags').fill('(Exact_Tag:1.2), Keep');await page.locator('#custom-tags').blur();await page.evaluate(()=>{CPW.state.saveToLibrary();CPW._autosave.flush()});await page.reload();assert(await page.evaluate(()=>CPW.state.outfit.presentation.seat==='armchair'&&CPW.state.outfit.presentation.preset==='seated'&&CPW.state.outfit.output.customTags==='(Exact_Tag:1.2), Keep'),'presentation save reload');
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'output horizontal overflow');
await page.locator('.presentation-panel summary').click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(screenshotDir,'phase5d-presentation-'+width+'.png'),fullPage:true});
const targets=await page.locator('.presentation-panel select, .presentation-panel button, .presentation-panel summary').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&(r.width<44||r.height<44)}).map(n=>n.textContent));assert(!targets.length,'presentation touch targets '+targets);
// Actual library duplication UI and complete browser test runner.
await page.evaluate(()=>location.hash='#/library');await page.getByRole('button',{name:'複製',exact:true}).first().click();assert(await page.evaluate(()=>CPW.store.listOutfits().length>=2),'library duplicate');
await page.goto('http://127.0.0.1:'+server.address().port+'/tests.html');assert(await page.evaluate(()=>CPW.runTests().failed===0),'browser full regression');
report.viewports.push({width,foodTwoStep:true,traditionalQipao:true,merfolk:true,confirmationCancel:true,preserveMode:true,presentation:true,outputScopes:true,libraryDuplicate:true,browserTests:true,preview:true,immutable:true,adopt:true,reload:true,reedit:true,noOverflow:true,tap44:true});await page.close();}
assert(!report.errors.length,report.errors.join('\n'));fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify(report));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
