/* Optional development QA; the published app remains dependency-free. */
const fs=require('fs'),path=require('path'),http=require('http'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||path.join(root,'verification/phase5e-ui.json'));
const screenshotDir=path.resolve(process.env.CPW_SCREENSHOT_DIR||path.join(path.dirname(out),'screenshots'));fs.mkdirSync(screenshotDir,{recursive:true});
const assert=(v,m)=>{if(!v)throw Error(m)};
const server=http.createServer((req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname),file=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:process.env.CPW_BROWSER_CHANNEL||'msedge'}),report={browser:browser.version(),viewports:[],errors:[],nativeSafari:'Not available; mobile touch emulation is not an iPhone native picker test.'};
try{for(const width of [375,390,430]){
 const context=await browser.newContext({viewport:{width,height:844},isMobile:true,hasTouch:true}),page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 await page.addInitScript(()=>{window.selectFocusCalls=[];const focus=HTMLElement.prototype.focus;HTMLElement.prototype.focus=function(...args){if(this.tagName==='SELECT')window.selectFocusCalls.push(this.id);return focus.apply(this,args);};});
 const noOverflow=async()=>assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);
 let changes=0;const choose=async(id,value)=>{await page.locator('#'+id).focus();await page.evaluate(()=>{window.selectFocusCalls=[]});await page.locator('#'+id).selectOption(value);assert(await page.evaluate(()=>window.selectFocusCalls.length===0),'automatic select refocus '+id);assert(await page.locator('#'+id).inputValue()===value,'selection retained '+id);changes++;await noOverflow();};
 const add=async(key,value)=>{await choose('cf-pick-'+key,value);await page.locator('#cf-add-'+key).click();};
 const step=async(n)=>{await page.getByRole('button',{name:['1 題材','2 世界・人物','3 デザイン','4 衣装','5 反映'][n-1],exact:true}).click();await noOverflow();};
 await page.goto('http://127.0.0.1:'+server.address().port+'/');
 assert(await page.getByRole('link',{name:'細かく選んで作る',exact:true}).count()===1,'home detailed');assert(await page.getByRole('link',{name:'コンセプトから作る',exact:true}).count()===1,'home concept');
 await page.getByRole('link',{name:'細かく選んで作る',exact:true}).click();await page.getByRole('heading',{name:'何から始める？',exact:true}).waitFor();assert(await page.locator('.card--tap').count()===5,'entry five routes');assert(await page.locator('a[href="#/concept_fashion"]').count()===0,'entry duplicate');
 for(const route of ['zero','worldview','garment','preset','motif']){await page.locator('a[href="#/setup/'+route+'"]').click();await page.locator('.screen button').first().waitFor();await page.locator('.screen button').first().click();await page.locator('#panel-concept').waitFor();assert(await page.evaluate(route=>CPW.state.outfit.entryMode===route,route),'entry route '+route);await page.evaluate(()=>{location.hash='#/entry'});await page.locator('a[href="#/setup/zero"]').waitFor();}
 await page.evaluate(()=>{CPW.state.load(CPW.schema.createOutfit());location.hash='#/';});await page.getByRole('link',{name:'コンセプトから作る',exact:true}).click();
 const before=await page.evaluate(()=>JSON.stringify(CPW.state.outfit));
 await choose('cf-categoryId','nature');await choose('cf-motifId','deep_sea');await page.locator('#cf-secondary-add').click();await choose('cf-secondary-categoryId','art');await choose('cf-secondary-motifId','gothic_cathedral');await choose('cf-blendMode','split_roles');
 await page.locator('#cf-secondary-remove').click();assert(await page.locator('#cf-secondary-motifId').count()===0,'secondary removed');await page.locator('#cf-secondary-add').click();await choose('cf-secondary-categoryId','art');await choose('cf-secondary-motifId','gothic_cathedral');
 await step(2);await choose('cf-context-worldviewId','western_fantasy');await choose('cf-context-eraId','victorian_era');await choose('cf-context-roleId','scholar');await choose('cf-context-occasionId','research');await add('context-storyStateIds','fallen_status');await add('context-storyStateIds','long_journey');await add('context-storyStateIds','after_battle');assert(await page.locator('[data-cf-selected^="context.storyStateIds:"]').count()===2,'story limit');
 await step(3);for(const id of ['mystical','elegant','cute'])await page.locator('[data-cf="directions:'+id+'"]').click();assert(await page.locator('[data-cf^="directions:"][aria-pressed="true"]').count()===2,'direction limit');await add('designLanguages','vertical');await add('designLanguages','organic');await add('designLanguages','linear');assert(await page.locator('[data-cf-selected^="designLanguages:"]').count()===2,'language limit');await choose('cf-interpretationMode','symbolic');
 await step(4);await choose('cf-baseId','gown');await step(5);for(const id of ['no_frills','no_lace','no_wings','no_halo','no_gems'])await add('exclusions',id);assert(await page.locator('[data-cf-selected^="exclusions:"]').count()===4,'exclusion limit');
 await page.locator('#cf-generate').click();assert(await page.locator('.cf-candidate').count()===3,'three strategies');assert(before===await page.evaluate(()=>JSON.stringify(CPW.state.outfit)),'preview mutation');for(const label of ['案A：モチーフを分かりやすく','案B：ファッションとして自然に','案C：大胆に再構成'])assert(await page.getByRole('heading',{name:label,exact:true}).count()===1,'strategy label');
 await page.locator('.cf-candidate summary').first().click();assert((await page.locator('.cf-candidate details').first().innerText()).includes('反映'),'details');await noOverflow();
 const small=await page.locator('.concept-wizard button,.concept-wizard select,.concept-wizard summary').evaluateAll(nodes=>nodes.filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&(r.width<44||r.height<44)}).map(n=>n.textContent));assert(!small.length,'44px targets '+small);
 await page.waitForFunction(()=>!document.querySelector('#toast').classList.contains('is-visible'));
 await page.screenshot({path:path.join(screenshotDir,'phase5e-candidates-'+width+'.png'),fullPage:true});
 await page.locator('[data-cf-adopt="0"]').click();await page.locator('#panel-concept').waitFor();await page.evaluate(()=>CPW._autosave.flush());await page.reload();assert(await page.evaluate(()=>CPW.state.outfit.concept.inspiration.secondary.motifId==='gothic_cathedral'),'saved secondary');assert(await page.evaluate(()=>CPW.state.outfit.version==='0.6'),'schema');
 await page.getByRole('link',{name:/コンセプトを編集/}).click();assert(await page.locator('#cf-secondary-motifId').inputValue()==='gothic_cathedral','edit secondary');await step(2);assert(await page.locator('#cf-context-roleId').inputValue()==='scholar','edit context');await step(1);
 await choose('cf-categoryId','food');assert(await page.locator('#cf-motifId').count()===0,'food group dependency');await choose('cf-foodGroupId','drinks');await choose('cf-motifId','cream_soda');await choose('cf-categoryId','traditional');await choose('cf-traditional-regionId','east_asia');await choose('cf-traditional-attireId','qipao');for(const [k,v] of [['qipaoNecklineId','classic'],['qipaoLengthId','long'],['qipaoSlitId','none'],['qipaoDrapeId','clean']])await choose('cf-traditional-'+k,v);
 await choose('cf-random-profile','dark');await page.locator('#cf-random').click();assert(await page.locator('#cf-categoryId').inputValue()!=='traditional','random avoids traditional');await step(3);assert(await page.locator('[data-cf="directions:dark"]').getAttribute('aria-pressed')==='true','random profile');
 // Both conflict choices plus cancellation are actual UI actions.
 for(const choice of ['keep','exclude']){
  await page.evaluate(()=>{CPW.state.load(CPW.schema.normalize({garment:{category:'dress',subtype:'cocktail_dress'},decorations:{items:[{type:'frills'}]},output:{customTags:'Exact custom'}}));location.hash='#/concept_fashion';});await page.locator('#cf-categoryId').waitFor();const original=await page.evaluate(()=>JSON.stringify(CPW.state.outfit));await choose('cf-categoryId','nature');await choose('cf-motifId','star');await step(4);await page.locator('[data-cf-mode="preserve"]').click();await step(5);await add('exclusions','no_frills');await page.locator('#cf-generate').click();assert((await page.locator('.cf-candidate').first().innerText()).includes('競合'),'conflict visible');await page.locator('[data-cf-adopt="0"]').click();await page.locator('[data-cf-conflict="cancel"]').click();assert(original===await page.evaluate(()=>JSON.stringify(CPW.state.outfit)),'cancel mutation');await page.locator('[data-cf-adopt="0"]').click();page.once('dialog',d=>d.accept());await page.locator('[data-cf-conflict="'+choice+'"]').click();await page.locator('#panel-concept').waitFor();assert(await page.evaluate(choice=>CPW.state.outfit.decorations.items.some(x=>x.type==='frills')===(choice==='keep'),choice),'conflict '+choice);assert(await page.evaluate(()=>CPW.state.outfit.output.customTags==='Exact custom'),'tags preserved');
 }
 await page.getByRole('link',{name:/コンセプトを編集/}).click();await step(5);await page.screenshot({path:path.join(screenshotDir,'phase5e-controls-'+width+'.png'),fullPage:true});await noOverflow();
 const bars=await page.evaluate(()=>{const a=document.querySelector('.topnav'),b=document.querySelector('.bottombar');return a&&b?a.getBoundingClientRect().bottom<=b.getBoundingClientRect().top:document.querySelector('.cf-steps').getBoundingClientRect().right<=innerWidth;});assert(bars,'nav overlap');
 await page.goto('http://127.0.0.1:'+server.address().port+'/tests.html');const tests=await page.evaluate(()=>CPW.runTests());assert(tests.failed===0,'browser regressions');
 report.viewports.push({width,selectChanges:changes,noAutomaticRefocus:true,entryFiveRoutes:true,fiveSteps:true,secondaryAddRemove:true,context:true,limits:true,random:true,threeStrategies:true,details:true,previewImmutable:true,adopt:true,preserveKeepExcludeCancel:true,saveReload:true,edit:true,dependentFood:true,qipao:true,noOverflow:true,tap44:true,tests:tests.passed});await context.close();
}assert(!report.errors.length,report.errors.join('\n'));fs.writeFileSync(out,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
